import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { task_statusesOrderByWithRelationInputObjectSchema as task_statusesOrderByWithRelationInputObjectSchema } from './objects/task_statusesOrderByWithRelationInput.schema';
import { task_statusesWhereInputObjectSchema as task_statusesWhereInputObjectSchema } from './objects/task_statusesWhereInput.schema';
import { task_statusesWhereUniqueInputObjectSchema as task_statusesWhereUniqueInputObjectSchema } from './objects/task_statusesWhereUniqueInput.schema';
import { Task_statusesCountAggregateInputObjectSchema as Task_statusesCountAggregateInputObjectSchema } from './objects/Task_statusesCountAggregateInput.schema';
import { Task_statusesMinAggregateInputObjectSchema as Task_statusesMinAggregateInputObjectSchema } from './objects/Task_statusesMinAggregateInput.schema';
import { Task_statusesMaxAggregateInputObjectSchema as Task_statusesMaxAggregateInputObjectSchema } from './objects/Task_statusesMaxAggregateInput.schema';
import { Task_statusesAvgAggregateInputObjectSchema as Task_statusesAvgAggregateInputObjectSchema } from './objects/Task_statusesAvgAggregateInput.schema';
import { Task_statusesSumAggregateInputObjectSchema as Task_statusesSumAggregateInputObjectSchema } from './objects/Task_statusesSumAggregateInput.schema';

export const task_statusesAggregateSchema: z.ZodType<Prisma.Task_statusesAggregateArgs> = z.object({ orderBy: z.union([task_statusesOrderByWithRelationInputObjectSchema, task_statusesOrderByWithRelationInputObjectSchema.array()]).optional(), where: task_statusesWhereInputObjectSchema.optional(), cursor: task_statusesWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Task_statusesCountAggregateInputObjectSchema ]).optional(), _min: Task_statusesMinAggregateInputObjectSchema.optional(), _max: Task_statusesMaxAggregateInputObjectSchema.optional(), _avg: Task_statusesAvgAggregateInputObjectSchema.optional(), _sum: Task_statusesSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.Task_statusesAggregateArgs>;

export const task_statusesAggregateZodSchema = z.object({ orderBy: z.union([task_statusesOrderByWithRelationInputObjectSchema, task_statusesOrderByWithRelationInputObjectSchema.array()]).optional(), where: task_statusesWhereInputObjectSchema.optional(), cursor: task_statusesWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Task_statusesCountAggregateInputObjectSchema ]).optional(), _min: Task_statusesMinAggregateInputObjectSchema.optional(), _max: Task_statusesMaxAggregateInputObjectSchema.optional(), _avg: Task_statusesAvgAggregateInputObjectSchema.optional(), _sum: Task_statusesSumAggregateInputObjectSchema.optional() }).strict();