import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { activity_logsOrderByWithRelationInputObjectSchema as activity_logsOrderByWithRelationInputObjectSchema } from './objects/activity_logsOrderByWithRelationInput.schema';
import { activity_logsWhereInputObjectSchema as activity_logsWhereInputObjectSchema } from './objects/activity_logsWhereInput.schema';
import { activity_logsWhereUniqueInputObjectSchema as activity_logsWhereUniqueInputObjectSchema } from './objects/activity_logsWhereUniqueInput.schema';
import { Activity_logsCountAggregateInputObjectSchema as Activity_logsCountAggregateInputObjectSchema } from './objects/Activity_logsCountAggregateInput.schema';
import { Activity_logsMinAggregateInputObjectSchema as Activity_logsMinAggregateInputObjectSchema } from './objects/Activity_logsMinAggregateInput.schema';
import { Activity_logsMaxAggregateInputObjectSchema as Activity_logsMaxAggregateInputObjectSchema } from './objects/Activity_logsMaxAggregateInput.schema';
import { Activity_logsAvgAggregateInputObjectSchema as Activity_logsAvgAggregateInputObjectSchema } from './objects/Activity_logsAvgAggregateInput.schema';
import { Activity_logsSumAggregateInputObjectSchema as Activity_logsSumAggregateInputObjectSchema } from './objects/Activity_logsSumAggregateInput.schema';

export const activity_logsAggregateSchema: z.ZodType<Prisma.Activity_logsAggregateArgs> = z.object({ orderBy: z.union([activity_logsOrderByWithRelationInputObjectSchema, activity_logsOrderByWithRelationInputObjectSchema.array()]).optional(), where: activity_logsWhereInputObjectSchema.optional(), cursor: activity_logsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Activity_logsCountAggregateInputObjectSchema ]).optional(), _min: Activity_logsMinAggregateInputObjectSchema.optional(), _max: Activity_logsMaxAggregateInputObjectSchema.optional(), _avg: Activity_logsAvgAggregateInputObjectSchema.optional(), _sum: Activity_logsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.Activity_logsAggregateArgs>;

export const activity_logsAggregateZodSchema = z.object({ orderBy: z.union([activity_logsOrderByWithRelationInputObjectSchema, activity_logsOrderByWithRelationInputObjectSchema.array()]).optional(), where: activity_logsWhereInputObjectSchema.optional(), cursor: activity_logsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Activity_logsCountAggregateInputObjectSchema ]).optional(), _min: Activity_logsMinAggregateInputObjectSchema.optional(), _max: Activity_logsMaxAggregateInputObjectSchema.optional(), _avg: Activity_logsAvgAggregateInputObjectSchema.optional(), _sum: Activity_logsSumAggregateInputObjectSchema.optional() }).strict();