import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { recycling_logOrderByWithRelationInputObjectSchema as recycling_logOrderByWithRelationInputObjectSchema } from './objects/recycling_logOrderByWithRelationInput.schema';
import { recycling_logWhereInputObjectSchema as recycling_logWhereInputObjectSchema } from './objects/recycling_logWhereInput.schema';
import { recycling_logWhereUniqueInputObjectSchema as recycling_logWhereUniqueInputObjectSchema } from './objects/recycling_logWhereUniqueInput.schema';
import { Recycling_logCountAggregateInputObjectSchema as Recycling_logCountAggregateInputObjectSchema } from './objects/Recycling_logCountAggregateInput.schema';
import { Recycling_logMinAggregateInputObjectSchema as Recycling_logMinAggregateInputObjectSchema } from './objects/Recycling_logMinAggregateInput.schema';
import { Recycling_logMaxAggregateInputObjectSchema as Recycling_logMaxAggregateInputObjectSchema } from './objects/Recycling_logMaxAggregateInput.schema';
import { Recycling_logAvgAggregateInputObjectSchema as Recycling_logAvgAggregateInputObjectSchema } from './objects/Recycling_logAvgAggregateInput.schema';
import { Recycling_logSumAggregateInputObjectSchema as Recycling_logSumAggregateInputObjectSchema } from './objects/Recycling_logSumAggregateInput.schema';

export const recycling_logAggregateSchema: z.ZodType<Prisma.Recycling_logAggregateArgs> = z.object({ orderBy: z.union([recycling_logOrderByWithRelationInputObjectSchema, recycling_logOrderByWithRelationInputObjectSchema.array()]).optional(), where: recycling_logWhereInputObjectSchema.optional(), cursor: recycling_logWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Recycling_logCountAggregateInputObjectSchema ]).optional(), _min: Recycling_logMinAggregateInputObjectSchema.optional(), _max: Recycling_logMaxAggregateInputObjectSchema.optional(), _avg: Recycling_logAvgAggregateInputObjectSchema.optional(), _sum: Recycling_logSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.Recycling_logAggregateArgs>;

export const recycling_logAggregateZodSchema = z.object({ orderBy: z.union([recycling_logOrderByWithRelationInputObjectSchema, recycling_logOrderByWithRelationInputObjectSchema.array()]).optional(), where: recycling_logWhereInputObjectSchema.optional(), cursor: recycling_logWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Recycling_logCountAggregateInputObjectSchema ]).optional(), _min: Recycling_logMinAggregateInputObjectSchema.optional(), _max: Recycling_logMaxAggregateInputObjectSchema.optional(), _avg: Recycling_logAvgAggregateInputObjectSchema.optional(), _sum: Recycling_logSumAggregateInputObjectSchema.optional() }).strict();