import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { process_template_stepsOrderByWithRelationInputObjectSchema as process_template_stepsOrderByWithRelationInputObjectSchema } from './objects/process_template_stepsOrderByWithRelationInput.schema';
import { process_template_stepsWhereInputObjectSchema as process_template_stepsWhereInputObjectSchema } from './objects/process_template_stepsWhereInput.schema';
import { process_template_stepsWhereUniqueInputObjectSchema as process_template_stepsWhereUniqueInputObjectSchema } from './objects/process_template_stepsWhereUniqueInput.schema';
import { Process_template_stepsCountAggregateInputObjectSchema as Process_template_stepsCountAggregateInputObjectSchema } from './objects/Process_template_stepsCountAggregateInput.schema';
import { Process_template_stepsMinAggregateInputObjectSchema as Process_template_stepsMinAggregateInputObjectSchema } from './objects/Process_template_stepsMinAggregateInput.schema';
import { Process_template_stepsMaxAggregateInputObjectSchema as Process_template_stepsMaxAggregateInputObjectSchema } from './objects/Process_template_stepsMaxAggregateInput.schema';
import { Process_template_stepsAvgAggregateInputObjectSchema as Process_template_stepsAvgAggregateInputObjectSchema } from './objects/Process_template_stepsAvgAggregateInput.schema';
import { Process_template_stepsSumAggregateInputObjectSchema as Process_template_stepsSumAggregateInputObjectSchema } from './objects/Process_template_stepsSumAggregateInput.schema';

export const process_template_stepsAggregateSchema: z.ZodType<Prisma.Process_template_stepsAggregateArgs> = z.object({ orderBy: z.union([process_template_stepsOrderByWithRelationInputObjectSchema, process_template_stepsOrderByWithRelationInputObjectSchema.array()]).optional(), where: process_template_stepsWhereInputObjectSchema.optional(), cursor: process_template_stepsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Process_template_stepsCountAggregateInputObjectSchema ]).optional(), _min: Process_template_stepsMinAggregateInputObjectSchema.optional(), _max: Process_template_stepsMaxAggregateInputObjectSchema.optional(), _avg: Process_template_stepsAvgAggregateInputObjectSchema.optional(), _sum: Process_template_stepsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.Process_template_stepsAggregateArgs>;

export const process_template_stepsAggregateZodSchema = z.object({ orderBy: z.union([process_template_stepsOrderByWithRelationInputObjectSchema, process_template_stepsOrderByWithRelationInputObjectSchema.array()]).optional(), where: process_template_stepsWhereInputObjectSchema.optional(), cursor: process_template_stepsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Process_template_stepsCountAggregateInputObjectSchema ]).optional(), _min: Process_template_stepsMinAggregateInputObjectSchema.optional(), _max: Process_template_stepsMaxAggregateInputObjectSchema.optional(), _avg: Process_template_stepsAvgAggregateInputObjectSchema.optional(), _sum: Process_template_stepsSumAggregateInputObjectSchema.optional() }).strict();