import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { process_templatesOrderByWithRelationInputObjectSchema as process_templatesOrderByWithRelationInputObjectSchema } from './objects/process_templatesOrderByWithRelationInput.schema';
import { process_templatesWhereInputObjectSchema as process_templatesWhereInputObjectSchema } from './objects/process_templatesWhereInput.schema';
import { process_templatesWhereUniqueInputObjectSchema as process_templatesWhereUniqueInputObjectSchema } from './objects/process_templatesWhereUniqueInput.schema';
import { Process_templatesCountAggregateInputObjectSchema as Process_templatesCountAggregateInputObjectSchema } from './objects/Process_templatesCountAggregateInput.schema';
import { Process_templatesMinAggregateInputObjectSchema as Process_templatesMinAggregateInputObjectSchema } from './objects/Process_templatesMinAggregateInput.schema';
import { Process_templatesMaxAggregateInputObjectSchema as Process_templatesMaxAggregateInputObjectSchema } from './objects/Process_templatesMaxAggregateInput.schema';
import { Process_templatesAvgAggregateInputObjectSchema as Process_templatesAvgAggregateInputObjectSchema } from './objects/Process_templatesAvgAggregateInput.schema';
import { Process_templatesSumAggregateInputObjectSchema as Process_templatesSumAggregateInputObjectSchema } from './objects/Process_templatesSumAggregateInput.schema';

export const process_templatesAggregateSchema: z.ZodType<Prisma.Process_templatesAggregateArgs> = z.object({ orderBy: z.union([process_templatesOrderByWithRelationInputObjectSchema, process_templatesOrderByWithRelationInputObjectSchema.array()]).optional(), where: process_templatesWhereInputObjectSchema.optional(), cursor: process_templatesWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Process_templatesCountAggregateInputObjectSchema ]).optional(), _min: Process_templatesMinAggregateInputObjectSchema.optional(), _max: Process_templatesMaxAggregateInputObjectSchema.optional(), _avg: Process_templatesAvgAggregateInputObjectSchema.optional(), _sum: Process_templatesSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.Process_templatesAggregateArgs>;

export const process_templatesAggregateZodSchema = z.object({ orderBy: z.union([process_templatesOrderByWithRelationInputObjectSchema, process_templatesOrderByWithRelationInputObjectSchema.array()]).optional(), where: process_templatesWhereInputObjectSchema.optional(), cursor: process_templatesWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Process_templatesCountAggregateInputObjectSchema ]).optional(), _min: Process_templatesMinAggregateInputObjectSchema.optional(), _max: Process_templatesMaxAggregateInputObjectSchema.optional(), _avg: Process_templatesAvgAggregateInputObjectSchema.optional(), _sum: Process_templatesSumAggregateInputObjectSchema.optional() }).strict();