import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { customersOrderByWithRelationInputObjectSchema as customersOrderByWithRelationInputObjectSchema } from './objects/customersOrderByWithRelationInput.schema';
import { customersWhereInputObjectSchema as customersWhereInputObjectSchema } from './objects/customersWhereInput.schema';
import { customersWhereUniqueInputObjectSchema as customersWhereUniqueInputObjectSchema } from './objects/customersWhereUniqueInput.schema';
import { CustomersCountAggregateInputObjectSchema as CustomersCountAggregateInputObjectSchema } from './objects/CustomersCountAggregateInput.schema';
import { CustomersMinAggregateInputObjectSchema as CustomersMinAggregateInputObjectSchema } from './objects/CustomersMinAggregateInput.schema';
import { CustomersMaxAggregateInputObjectSchema as CustomersMaxAggregateInputObjectSchema } from './objects/CustomersMaxAggregateInput.schema';
import { CustomersAvgAggregateInputObjectSchema as CustomersAvgAggregateInputObjectSchema } from './objects/CustomersAvgAggregateInput.schema';
import { CustomersSumAggregateInputObjectSchema as CustomersSumAggregateInputObjectSchema } from './objects/CustomersSumAggregateInput.schema';

export const customersAggregateSchema: z.ZodType<Prisma.customersAggregateArgs> = z.object({ orderBy: z.union([customersOrderByWithRelationInputObjectSchema, customersOrderByWithRelationInputObjectSchema.array()]).optional(), where: customersWhereInputObjectSchema.optional(), cursor: customersWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), CustomersCountAggregateInputObjectSchema ]).optional(), _min: CustomersMinAggregateInputObjectSchema.optional(), _max: CustomersMaxAggregateInputObjectSchema.optional(), _avg: CustomersAvgAggregateInputObjectSchema.optional(), _sum: CustomersSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.customersAggregateArgs>;

export const customersAggregateZodSchema = z.object({ orderBy: z.union([customersOrderByWithRelationInputObjectSchema, customersOrderByWithRelationInputObjectSchema.array()]).optional(), where: customersWhereInputObjectSchema.optional(), cursor: customersWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), CustomersCountAggregateInputObjectSchema ]).optional(), _min: CustomersMinAggregateInputObjectSchema.optional(), _max: CustomersMaxAggregateInputObjectSchema.optional(), _avg: CustomersAvgAggregateInputObjectSchema.optional(), _sum: CustomersSumAggregateInputObjectSchema.optional() }).strict();