import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { activity_logOrderByWithRelationInputObjectSchema as activity_logOrderByWithRelationInputObjectSchema } from './objects/activity_logOrderByWithRelationInput.schema';
import { activity_logWhereInputObjectSchema as activity_logWhereInputObjectSchema } from './objects/activity_logWhereInput.schema';
import { activity_logWhereUniqueInputObjectSchema as activity_logWhereUniqueInputObjectSchema } from './objects/activity_logWhereUniqueInput.schema';
import { Activity_logCountAggregateInputObjectSchema as Activity_logCountAggregateInputObjectSchema } from './objects/Activity_logCountAggregateInput.schema';
import { Activity_logMinAggregateInputObjectSchema as Activity_logMinAggregateInputObjectSchema } from './objects/Activity_logMinAggregateInput.schema';
import { Activity_logMaxAggregateInputObjectSchema as Activity_logMaxAggregateInputObjectSchema } from './objects/Activity_logMaxAggregateInput.schema';
import { Activity_logAvgAggregateInputObjectSchema as Activity_logAvgAggregateInputObjectSchema } from './objects/Activity_logAvgAggregateInput.schema';
import { Activity_logSumAggregateInputObjectSchema as Activity_logSumAggregateInputObjectSchema } from './objects/Activity_logSumAggregateInput.schema';

export const activity_logAggregateSchema: z.ZodType<Prisma.Activity_logAggregateArgs> = z.object({ orderBy: z.union([activity_logOrderByWithRelationInputObjectSchema, activity_logOrderByWithRelationInputObjectSchema.array()]).optional(), where: activity_logWhereInputObjectSchema.optional(), cursor: activity_logWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Activity_logCountAggregateInputObjectSchema ]).optional(), _min: Activity_logMinAggregateInputObjectSchema.optional(), _max: Activity_logMaxAggregateInputObjectSchema.optional(), _avg: Activity_logAvgAggregateInputObjectSchema.optional(), _sum: Activity_logSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.Activity_logAggregateArgs>;

export const activity_logAggregateZodSchema = z.object({ orderBy: z.union([activity_logOrderByWithRelationInputObjectSchema, activity_logOrderByWithRelationInputObjectSchema.array()]).optional(), where: activity_logWhereInputObjectSchema.optional(), cursor: activity_logWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Activity_logCountAggregateInputObjectSchema ]).optional(), _min: Activity_logMinAggregateInputObjectSchema.optional(), _max: Activity_logMaxAggregateInputObjectSchema.optional(), _avg: Activity_logAvgAggregateInputObjectSchema.optional(), _sum: Activity_logSumAggregateInputObjectSchema.optional() }).strict();