import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { process_instancesOrderByWithRelationInputObjectSchema as process_instancesOrderByWithRelationInputObjectSchema } from './objects/process_instancesOrderByWithRelationInput.schema';
import { process_instancesWhereInputObjectSchema as process_instancesWhereInputObjectSchema } from './objects/process_instancesWhereInput.schema';
import { process_instancesWhereUniqueInputObjectSchema as process_instancesWhereUniqueInputObjectSchema } from './objects/process_instancesWhereUniqueInput.schema';
import { Process_instancesCountAggregateInputObjectSchema as Process_instancesCountAggregateInputObjectSchema } from './objects/Process_instancesCountAggregateInput.schema';
import { Process_instancesMinAggregateInputObjectSchema as Process_instancesMinAggregateInputObjectSchema } from './objects/Process_instancesMinAggregateInput.schema';
import { Process_instancesMaxAggregateInputObjectSchema as Process_instancesMaxAggregateInputObjectSchema } from './objects/Process_instancesMaxAggregateInput.schema';
import { Process_instancesAvgAggregateInputObjectSchema as Process_instancesAvgAggregateInputObjectSchema } from './objects/Process_instancesAvgAggregateInput.schema';
import { Process_instancesSumAggregateInputObjectSchema as Process_instancesSumAggregateInputObjectSchema } from './objects/Process_instancesSumAggregateInput.schema';

export const process_instancesAggregateSchema: z.ZodType<Prisma.Process_instancesAggregateArgs> = z.object({ orderBy: z.union([process_instancesOrderByWithRelationInputObjectSchema, process_instancesOrderByWithRelationInputObjectSchema.array()]).optional(), where: process_instancesWhereInputObjectSchema.optional(), cursor: process_instancesWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Process_instancesCountAggregateInputObjectSchema ]).optional(), _min: Process_instancesMinAggregateInputObjectSchema.optional(), _max: Process_instancesMaxAggregateInputObjectSchema.optional(), _avg: Process_instancesAvgAggregateInputObjectSchema.optional(), _sum: Process_instancesSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.Process_instancesAggregateArgs>;

export const process_instancesAggregateZodSchema = z.object({ orderBy: z.union([process_instancesOrderByWithRelationInputObjectSchema, process_instancesOrderByWithRelationInputObjectSchema.array()]).optional(), where: process_instancesWhereInputObjectSchema.optional(), cursor: process_instancesWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Process_instancesCountAggregateInputObjectSchema ]).optional(), _min: Process_instancesMinAggregateInputObjectSchema.optional(), _max: Process_instancesMaxAggregateInputObjectSchema.optional(), _avg: Process_instancesAvgAggregateInputObjectSchema.optional(), _sum: Process_instancesSumAggregateInputObjectSchema.optional() }).strict();