import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { attendanceOrderByWithRelationInputObjectSchema as attendanceOrderByWithRelationInputObjectSchema } from './objects/attendanceOrderByWithRelationInput.schema';
import { attendanceWhereInputObjectSchema as attendanceWhereInputObjectSchema } from './objects/attendanceWhereInput.schema';
import { attendanceWhereUniqueInputObjectSchema as attendanceWhereUniqueInputObjectSchema } from './objects/attendanceWhereUniqueInput.schema';
import { AttendanceCountAggregateInputObjectSchema as AttendanceCountAggregateInputObjectSchema } from './objects/AttendanceCountAggregateInput.schema';
import { AttendanceMinAggregateInputObjectSchema as AttendanceMinAggregateInputObjectSchema } from './objects/AttendanceMinAggregateInput.schema';
import { AttendanceMaxAggregateInputObjectSchema as AttendanceMaxAggregateInputObjectSchema } from './objects/AttendanceMaxAggregateInput.schema';
import { AttendanceAvgAggregateInputObjectSchema as AttendanceAvgAggregateInputObjectSchema } from './objects/AttendanceAvgAggregateInput.schema';
import { AttendanceSumAggregateInputObjectSchema as AttendanceSumAggregateInputObjectSchema } from './objects/AttendanceSumAggregateInput.schema';

export const attendanceAggregateSchema: z.ZodType<Prisma.attendanceAggregateArgs> = z.object({ orderBy: z.union([attendanceOrderByWithRelationInputObjectSchema, attendanceOrderByWithRelationInputObjectSchema.array()]).optional(), where: attendanceWhereInputObjectSchema.optional(), cursor: attendanceWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), AttendanceCountAggregateInputObjectSchema ]).optional(), _min: AttendanceMinAggregateInputObjectSchema.optional(), _max: AttendanceMaxAggregateInputObjectSchema.optional(), _avg: AttendanceAvgAggregateInputObjectSchema.optional(), _sum: AttendanceSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.attendanceAggregateArgs>;

export const attendanceAggregateZodSchema = z.object({ orderBy: z.union([attendanceOrderByWithRelationInputObjectSchema, attendanceOrderByWithRelationInputObjectSchema.array()]).optional(), where: attendanceWhereInputObjectSchema.optional(), cursor: attendanceWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), AttendanceCountAggregateInputObjectSchema ]).optional(), _min: AttendanceMinAggregateInputObjectSchema.optional(), _max: AttendanceMaxAggregateInputObjectSchema.optional(), _avg: AttendanceAvgAggregateInputObjectSchema.optional(), _sum: AttendanceSumAggregateInputObjectSchema.optional() }).strict();