import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { process_instance_stepsOrderByWithRelationInputObjectSchema as process_instance_stepsOrderByWithRelationInputObjectSchema } from './objects/process_instance_stepsOrderByWithRelationInput.schema';
import { process_instance_stepsWhereInputObjectSchema as process_instance_stepsWhereInputObjectSchema } from './objects/process_instance_stepsWhereInput.schema';
import { process_instance_stepsWhereUniqueInputObjectSchema as process_instance_stepsWhereUniqueInputObjectSchema } from './objects/process_instance_stepsWhereUniqueInput.schema';
import { Process_instance_stepsCountAggregateInputObjectSchema as Process_instance_stepsCountAggregateInputObjectSchema } from './objects/Process_instance_stepsCountAggregateInput.schema';
import { Process_instance_stepsMinAggregateInputObjectSchema as Process_instance_stepsMinAggregateInputObjectSchema } from './objects/Process_instance_stepsMinAggregateInput.schema';
import { Process_instance_stepsMaxAggregateInputObjectSchema as Process_instance_stepsMaxAggregateInputObjectSchema } from './objects/Process_instance_stepsMaxAggregateInput.schema';
import { Process_instance_stepsAvgAggregateInputObjectSchema as Process_instance_stepsAvgAggregateInputObjectSchema } from './objects/Process_instance_stepsAvgAggregateInput.schema';
import { Process_instance_stepsSumAggregateInputObjectSchema as Process_instance_stepsSumAggregateInputObjectSchema } from './objects/Process_instance_stepsSumAggregateInput.schema';

export const process_instance_stepsAggregateSchema: z.ZodType<Prisma.Process_instance_stepsAggregateArgs> = z.object({ orderBy: z.union([process_instance_stepsOrderByWithRelationInputObjectSchema, process_instance_stepsOrderByWithRelationInputObjectSchema.array()]).optional(), where: process_instance_stepsWhereInputObjectSchema.optional(), cursor: process_instance_stepsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Process_instance_stepsCountAggregateInputObjectSchema ]).optional(), _min: Process_instance_stepsMinAggregateInputObjectSchema.optional(), _max: Process_instance_stepsMaxAggregateInputObjectSchema.optional(), _avg: Process_instance_stepsAvgAggregateInputObjectSchema.optional(), _sum: Process_instance_stepsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.Process_instance_stepsAggregateArgs>;

export const process_instance_stepsAggregateZodSchema = z.object({ orderBy: z.union([process_instance_stepsOrderByWithRelationInputObjectSchema, process_instance_stepsOrderByWithRelationInputObjectSchema.array()]).optional(), where: process_instance_stepsWhereInputObjectSchema.optional(), cursor: process_instance_stepsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Process_instance_stepsCountAggregateInputObjectSchema ]).optional(), _min: Process_instance_stepsMinAggregateInputObjectSchema.optional(), _max: Process_instance_stepsMaxAggregateInputObjectSchema.optional(), _avg: Process_instance_stepsAvgAggregateInputObjectSchema.optional(), _sum: Process_instance_stepsSumAggregateInputObjectSchema.optional() }).strict();