import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { order_logsOrderByWithRelationInputObjectSchema as order_logsOrderByWithRelationInputObjectSchema } from './objects/order_logsOrderByWithRelationInput.schema';
import { order_logsWhereInputObjectSchema as order_logsWhereInputObjectSchema } from './objects/order_logsWhereInput.schema';
import { order_logsWhereUniqueInputObjectSchema as order_logsWhereUniqueInputObjectSchema } from './objects/order_logsWhereUniqueInput.schema';
import { Order_logsCountAggregateInputObjectSchema as Order_logsCountAggregateInputObjectSchema } from './objects/Order_logsCountAggregateInput.schema';
import { Order_logsMinAggregateInputObjectSchema as Order_logsMinAggregateInputObjectSchema } from './objects/Order_logsMinAggregateInput.schema';
import { Order_logsMaxAggregateInputObjectSchema as Order_logsMaxAggregateInputObjectSchema } from './objects/Order_logsMaxAggregateInput.schema';
import { Order_logsAvgAggregateInputObjectSchema as Order_logsAvgAggregateInputObjectSchema } from './objects/Order_logsAvgAggregateInput.schema';
import { Order_logsSumAggregateInputObjectSchema as Order_logsSumAggregateInputObjectSchema } from './objects/Order_logsSumAggregateInput.schema';

export const order_logsAggregateSchema: z.ZodType<Prisma.Order_logsAggregateArgs> = z.object({ orderBy: z.union([order_logsOrderByWithRelationInputObjectSchema, order_logsOrderByWithRelationInputObjectSchema.array()]).optional(), where: order_logsWhereInputObjectSchema.optional(), cursor: order_logsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Order_logsCountAggregateInputObjectSchema ]).optional(), _min: Order_logsMinAggregateInputObjectSchema.optional(), _max: Order_logsMaxAggregateInputObjectSchema.optional(), _avg: Order_logsAvgAggregateInputObjectSchema.optional(), _sum: Order_logsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.Order_logsAggregateArgs>;

export const order_logsAggregateZodSchema = z.object({ orderBy: z.union([order_logsOrderByWithRelationInputObjectSchema, order_logsOrderByWithRelationInputObjectSchema.array()]).optional(), where: order_logsWhereInputObjectSchema.optional(), cursor: order_logsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Order_logsCountAggregateInputObjectSchema ]).optional(), _min: Order_logsMinAggregateInputObjectSchema.optional(), _max: Order_logsMaxAggregateInputObjectSchema.optional(), _avg: Order_logsAvgAggregateInputObjectSchema.optional(), _sum: Order_logsSumAggregateInputObjectSchema.optional() }).strict();