import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { request_statusesOrderByWithRelationInputObjectSchema as request_statusesOrderByWithRelationInputObjectSchema } from './objects/request_statusesOrderByWithRelationInput.schema';
import { request_statusesWhereInputObjectSchema as request_statusesWhereInputObjectSchema } from './objects/request_statusesWhereInput.schema';
import { request_statusesWhereUniqueInputObjectSchema as request_statusesWhereUniqueInputObjectSchema } from './objects/request_statusesWhereUniqueInput.schema';
import { Request_statusesCountAggregateInputObjectSchema as Request_statusesCountAggregateInputObjectSchema } from './objects/Request_statusesCountAggregateInput.schema';
import { Request_statusesMinAggregateInputObjectSchema as Request_statusesMinAggregateInputObjectSchema } from './objects/Request_statusesMinAggregateInput.schema';
import { Request_statusesMaxAggregateInputObjectSchema as Request_statusesMaxAggregateInputObjectSchema } from './objects/Request_statusesMaxAggregateInput.schema';
import { Request_statusesAvgAggregateInputObjectSchema as Request_statusesAvgAggregateInputObjectSchema } from './objects/Request_statusesAvgAggregateInput.schema';
import { Request_statusesSumAggregateInputObjectSchema as Request_statusesSumAggregateInputObjectSchema } from './objects/Request_statusesSumAggregateInput.schema';

export const request_statusesAggregateSchema: z.ZodType<Prisma.Request_statusesAggregateArgs> = z.object({ orderBy: z.union([request_statusesOrderByWithRelationInputObjectSchema, request_statusesOrderByWithRelationInputObjectSchema.array()]).optional(), where: request_statusesWhereInputObjectSchema.optional(), cursor: request_statusesWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Request_statusesCountAggregateInputObjectSchema ]).optional(), _min: Request_statusesMinAggregateInputObjectSchema.optional(), _max: Request_statusesMaxAggregateInputObjectSchema.optional(), _avg: Request_statusesAvgAggregateInputObjectSchema.optional(), _sum: Request_statusesSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.Request_statusesAggregateArgs>;

export const request_statusesAggregateZodSchema = z.object({ orderBy: z.union([request_statusesOrderByWithRelationInputObjectSchema, request_statusesOrderByWithRelationInputObjectSchema.array()]).optional(), where: request_statusesWhereInputObjectSchema.optional(), cursor: request_statusesWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Request_statusesCountAggregateInputObjectSchema ]).optional(), _min: Request_statusesMinAggregateInputObjectSchema.optional(), _max: Request_statusesMaxAggregateInputObjectSchema.optional(), _avg: Request_statusesAvgAggregateInputObjectSchema.optional(), _sum: Request_statusesSumAggregateInputObjectSchema.optional() }).strict();