import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { step_actionsOrderByWithRelationInputObjectSchema as step_actionsOrderByWithRelationInputObjectSchema } from './objects/step_actionsOrderByWithRelationInput.schema';
import { step_actionsWhereInputObjectSchema as step_actionsWhereInputObjectSchema } from './objects/step_actionsWhereInput.schema';
import { step_actionsWhereUniqueInputObjectSchema as step_actionsWhereUniqueInputObjectSchema } from './objects/step_actionsWhereUniqueInput.schema';
import { Step_actionsCountAggregateInputObjectSchema as Step_actionsCountAggregateInputObjectSchema } from './objects/Step_actionsCountAggregateInput.schema';
import { Step_actionsMinAggregateInputObjectSchema as Step_actionsMinAggregateInputObjectSchema } from './objects/Step_actionsMinAggregateInput.schema';
import { Step_actionsMaxAggregateInputObjectSchema as Step_actionsMaxAggregateInputObjectSchema } from './objects/Step_actionsMaxAggregateInput.schema';
import { Step_actionsAvgAggregateInputObjectSchema as Step_actionsAvgAggregateInputObjectSchema } from './objects/Step_actionsAvgAggregateInput.schema';
import { Step_actionsSumAggregateInputObjectSchema as Step_actionsSumAggregateInputObjectSchema } from './objects/Step_actionsSumAggregateInput.schema';

export const step_actionsAggregateSchema: z.ZodType<Prisma.Step_actionsAggregateArgs> = z.object({ orderBy: z.union([step_actionsOrderByWithRelationInputObjectSchema, step_actionsOrderByWithRelationInputObjectSchema.array()]).optional(), where: step_actionsWhereInputObjectSchema.optional(), cursor: step_actionsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Step_actionsCountAggregateInputObjectSchema ]).optional(), _min: Step_actionsMinAggregateInputObjectSchema.optional(), _max: Step_actionsMaxAggregateInputObjectSchema.optional(), _avg: Step_actionsAvgAggregateInputObjectSchema.optional(), _sum: Step_actionsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.Step_actionsAggregateArgs>;

export const step_actionsAggregateZodSchema = z.object({ orderBy: z.union([step_actionsOrderByWithRelationInputObjectSchema, step_actionsOrderByWithRelationInputObjectSchema.array()]).optional(), where: step_actionsWhereInputObjectSchema.optional(), cursor: step_actionsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Step_actionsCountAggregateInputObjectSchema ]).optional(), _min: Step_actionsMinAggregateInputObjectSchema.optional(), _max: Step_actionsMaxAggregateInputObjectSchema.optional(), _avg: Step_actionsAvgAggregateInputObjectSchema.optional(), _sum: Step_actionsSumAggregateInputObjectSchema.optional() }).strict();