import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { materialsOrderByWithRelationInputObjectSchema as materialsOrderByWithRelationInputObjectSchema } from './objects/materialsOrderByWithRelationInput.schema';
import { materialsWhereInputObjectSchema as materialsWhereInputObjectSchema } from './objects/materialsWhereInput.schema';
import { materialsWhereUniqueInputObjectSchema as materialsWhereUniqueInputObjectSchema } from './objects/materialsWhereUniqueInput.schema';
import { MaterialsCountAggregateInputObjectSchema as MaterialsCountAggregateInputObjectSchema } from './objects/MaterialsCountAggregateInput.schema';
import { MaterialsMinAggregateInputObjectSchema as MaterialsMinAggregateInputObjectSchema } from './objects/MaterialsMinAggregateInput.schema';
import { MaterialsMaxAggregateInputObjectSchema as MaterialsMaxAggregateInputObjectSchema } from './objects/MaterialsMaxAggregateInput.schema';
import { MaterialsAvgAggregateInputObjectSchema as MaterialsAvgAggregateInputObjectSchema } from './objects/MaterialsAvgAggregateInput.schema';
import { MaterialsSumAggregateInputObjectSchema as MaterialsSumAggregateInputObjectSchema } from './objects/MaterialsSumAggregateInput.schema';

export const materialsAggregateSchema: z.ZodType<Prisma.materialsAggregateArgs> = z.object({ orderBy: z.union([materialsOrderByWithRelationInputObjectSchema, materialsOrderByWithRelationInputObjectSchema.array()]).optional(), where: materialsWhereInputObjectSchema.optional(), cursor: materialsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), MaterialsCountAggregateInputObjectSchema ]).optional(), _min: MaterialsMinAggregateInputObjectSchema.optional(), _max: MaterialsMaxAggregateInputObjectSchema.optional(), _avg: MaterialsAvgAggregateInputObjectSchema.optional(), _sum: MaterialsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.materialsAggregateArgs>;

export const materialsAggregateZodSchema = z.object({ orderBy: z.union([materialsOrderByWithRelationInputObjectSchema, materialsOrderByWithRelationInputObjectSchema.array()]).optional(), where: materialsWhereInputObjectSchema.optional(), cursor: materialsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), MaterialsCountAggregateInputObjectSchema ]).optional(), _min: MaterialsMinAggregateInputObjectSchema.optional(), _max: MaterialsMaxAggregateInputObjectSchema.optional(), _avg: MaterialsAvgAggregateInputObjectSchema.optional(), _sum: MaterialsSumAggregateInputObjectSchema.optional() }).strict();