import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { process_logsOrderByWithRelationInputObjectSchema as process_logsOrderByWithRelationInputObjectSchema } from './objects/process_logsOrderByWithRelationInput.schema';
import { process_logsWhereInputObjectSchema as process_logsWhereInputObjectSchema } from './objects/process_logsWhereInput.schema';
import { process_logsWhereUniqueInputObjectSchema as process_logsWhereUniqueInputObjectSchema } from './objects/process_logsWhereUniqueInput.schema';
import { Process_logsCountAggregateInputObjectSchema as Process_logsCountAggregateInputObjectSchema } from './objects/Process_logsCountAggregateInput.schema';
import { Process_logsMinAggregateInputObjectSchema as Process_logsMinAggregateInputObjectSchema } from './objects/Process_logsMinAggregateInput.schema';
import { Process_logsMaxAggregateInputObjectSchema as Process_logsMaxAggregateInputObjectSchema } from './objects/Process_logsMaxAggregateInput.schema';
import { Process_logsAvgAggregateInputObjectSchema as Process_logsAvgAggregateInputObjectSchema } from './objects/Process_logsAvgAggregateInput.schema';
import { Process_logsSumAggregateInputObjectSchema as Process_logsSumAggregateInputObjectSchema } from './objects/Process_logsSumAggregateInput.schema';

export const process_logsAggregateSchema: z.ZodType<Prisma.Process_logsAggregateArgs> = z.object({ orderBy: z.union([process_logsOrderByWithRelationInputObjectSchema, process_logsOrderByWithRelationInputObjectSchema.array()]).optional(), where: process_logsWhereInputObjectSchema.optional(), cursor: process_logsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Process_logsCountAggregateInputObjectSchema ]).optional(), _min: Process_logsMinAggregateInputObjectSchema.optional(), _max: Process_logsMaxAggregateInputObjectSchema.optional(), _avg: Process_logsAvgAggregateInputObjectSchema.optional(), _sum: Process_logsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.Process_logsAggregateArgs>;

export const process_logsAggregateZodSchema = z.object({ orderBy: z.union([process_logsOrderByWithRelationInputObjectSchema, process_logsOrderByWithRelationInputObjectSchema.array()]).optional(), where: process_logsWhereInputObjectSchema.optional(), cursor: process_logsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Process_logsCountAggregateInputObjectSchema ]).optional(), _min: Process_logsMinAggregateInputObjectSchema.optional(), _max: Process_logsMaxAggregateInputObjectSchema.optional(), _avg: Process_logsAvgAggregateInputObjectSchema.optional(), _sum: Process_logsSumAggregateInputObjectSchema.optional() }).strict();