import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { product_variantsOrderByWithRelationInputObjectSchema as product_variantsOrderByWithRelationInputObjectSchema } from './objects/product_variantsOrderByWithRelationInput.schema';
import { product_variantsWhereInputObjectSchema as product_variantsWhereInputObjectSchema } from './objects/product_variantsWhereInput.schema';
import { product_variantsWhereUniqueInputObjectSchema as product_variantsWhereUniqueInputObjectSchema } from './objects/product_variantsWhereUniqueInput.schema';
import { Product_variantsCountAggregateInputObjectSchema as Product_variantsCountAggregateInputObjectSchema } from './objects/Product_variantsCountAggregateInput.schema';
import { Product_variantsMinAggregateInputObjectSchema as Product_variantsMinAggregateInputObjectSchema } from './objects/Product_variantsMinAggregateInput.schema';
import { Product_variantsMaxAggregateInputObjectSchema as Product_variantsMaxAggregateInputObjectSchema } from './objects/Product_variantsMaxAggregateInput.schema';
import { Product_variantsAvgAggregateInputObjectSchema as Product_variantsAvgAggregateInputObjectSchema } from './objects/Product_variantsAvgAggregateInput.schema';
import { Product_variantsSumAggregateInputObjectSchema as Product_variantsSumAggregateInputObjectSchema } from './objects/Product_variantsSumAggregateInput.schema';

export const product_variantsAggregateSchema: z.ZodType<Prisma.Product_variantsAggregateArgs> = z.object({ orderBy: z.union([product_variantsOrderByWithRelationInputObjectSchema, product_variantsOrderByWithRelationInputObjectSchema.array()]).optional(), where: product_variantsWhereInputObjectSchema.optional(), cursor: product_variantsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Product_variantsCountAggregateInputObjectSchema ]).optional(), _min: Product_variantsMinAggregateInputObjectSchema.optional(), _max: Product_variantsMaxAggregateInputObjectSchema.optional(), _avg: Product_variantsAvgAggregateInputObjectSchema.optional(), _sum: Product_variantsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.Product_variantsAggregateArgs>;

export const product_variantsAggregateZodSchema = z.object({ orderBy: z.union([product_variantsOrderByWithRelationInputObjectSchema, product_variantsOrderByWithRelationInputObjectSchema.array()]).optional(), where: product_variantsWhereInputObjectSchema.optional(), cursor: product_variantsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Product_variantsCountAggregateInputObjectSchema ]).optional(), _min: Product_variantsMinAggregateInputObjectSchema.optional(), _max: Product_variantsMaxAggregateInputObjectSchema.optional(), _avg: Product_variantsAvgAggregateInputObjectSchema.optional(), _sum: Product_variantsSumAggregateInputObjectSchema.optional() }).strict();