import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { printersOrderByWithRelationInputObjectSchema as printersOrderByWithRelationInputObjectSchema } from './objects/printersOrderByWithRelationInput.schema';
import { printersWhereInputObjectSchema as printersWhereInputObjectSchema } from './objects/printersWhereInput.schema';
import { printersWhereUniqueInputObjectSchema as printersWhereUniqueInputObjectSchema } from './objects/printersWhereUniqueInput.schema';
import { PrintersCountAggregateInputObjectSchema as PrintersCountAggregateInputObjectSchema } from './objects/PrintersCountAggregateInput.schema';
import { PrintersMinAggregateInputObjectSchema as PrintersMinAggregateInputObjectSchema } from './objects/PrintersMinAggregateInput.schema';
import { PrintersMaxAggregateInputObjectSchema as PrintersMaxAggregateInputObjectSchema } from './objects/PrintersMaxAggregateInput.schema';
import { PrintersAvgAggregateInputObjectSchema as PrintersAvgAggregateInputObjectSchema } from './objects/PrintersAvgAggregateInput.schema';
import { PrintersSumAggregateInputObjectSchema as PrintersSumAggregateInputObjectSchema } from './objects/PrintersSumAggregateInput.schema';

export const printersAggregateSchema: z.ZodType<Prisma.printersAggregateArgs> = z.object({ orderBy: z.union([printersOrderByWithRelationInputObjectSchema, printersOrderByWithRelationInputObjectSchema.array()]).optional(), where: printersWhereInputObjectSchema.optional(), cursor: printersWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), PrintersCountAggregateInputObjectSchema ]).optional(), _min: PrintersMinAggregateInputObjectSchema.optional(), _max: PrintersMaxAggregateInputObjectSchema.optional(), _avg: PrintersAvgAggregateInputObjectSchema.optional(), _sum: PrintersSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.printersAggregateArgs>;

export const printersAggregateZodSchema = z.object({ orderBy: z.union([printersOrderByWithRelationInputObjectSchema, printersOrderByWithRelationInputObjectSchema.array()]).optional(), where: printersWhereInputObjectSchema.optional(), cursor: printersWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), PrintersCountAggregateInputObjectSchema ]).optional(), _min: PrintersMinAggregateInputObjectSchema.optional(), _max: PrintersMaxAggregateInputObjectSchema.optional(), _avg: PrintersAvgAggregateInputObjectSchema.optional(), _sum: PrintersSumAggregateInputObjectSchema.optional() }).strict();