import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { shop_sectionsOrderByWithRelationInputObjectSchema as shop_sectionsOrderByWithRelationInputObjectSchema } from './objects/shop_sectionsOrderByWithRelationInput.schema';
import { shop_sectionsWhereInputObjectSchema as shop_sectionsWhereInputObjectSchema } from './objects/shop_sectionsWhereInput.schema';
import { shop_sectionsWhereUniqueInputObjectSchema as shop_sectionsWhereUniqueInputObjectSchema } from './objects/shop_sectionsWhereUniqueInput.schema';
import { Shop_sectionsCountAggregateInputObjectSchema as Shop_sectionsCountAggregateInputObjectSchema } from './objects/Shop_sectionsCountAggregateInput.schema';
import { Shop_sectionsMinAggregateInputObjectSchema as Shop_sectionsMinAggregateInputObjectSchema } from './objects/Shop_sectionsMinAggregateInput.schema';
import { Shop_sectionsMaxAggregateInputObjectSchema as Shop_sectionsMaxAggregateInputObjectSchema } from './objects/Shop_sectionsMaxAggregateInput.schema';
import { Shop_sectionsAvgAggregateInputObjectSchema as Shop_sectionsAvgAggregateInputObjectSchema } from './objects/Shop_sectionsAvgAggregateInput.schema';
import { Shop_sectionsSumAggregateInputObjectSchema as Shop_sectionsSumAggregateInputObjectSchema } from './objects/Shop_sectionsSumAggregateInput.schema';

export const shop_sectionsAggregateSchema: z.ZodType<Prisma.Shop_sectionsAggregateArgs> = z.object({ orderBy: z.union([shop_sectionsOrderByWithRelationInputObjectSchema, shop_sectionsOrderByWithRelationInputObjectSchema.array()]).optional(), where: shop_sectionsWhereInputObjectSchema.optional(), cursor: shop_sectionsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Shop_sectionsCountAggregateInputObjectSchema ]).optional(), _min: Shop_sectionsMinAggregateInputObjectSchema.optional(), _max: Shop_sectionsMaxAggregateInputObjectSchema.optional(), _avg: Shop_sectionsAvgAggregateInputObjectSchema.optional(), _sum: Shop_sectionsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.Shop_sectionsAggregateArgs>;

export const shop_sectionsAggregateZodSchema = z.object({ orderBy: z.union([shop_sectionsOrderByWithRelationInputObjectSchema, shop_sectionsOrderByWithRelationInputObjectSchema.array()]).optional(), where: shop_sectionsWhereInputObjectSchema.optional(), cursor: shop_sectionsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Shop_sectionsCountAggregateInputObjectSchema ]).optional(), _min: Shop_sectionsMinAggregateInputObjectSchema.optional(), _max: Shop_sectionsMaxAggregateInputObjectSchema.optional(), _avg: Shop_sectionsAvgAggregateInputObjectSchema.optional(), _sum: Shop_sectionsSumAggregateInputObjectSchema.optional() }).strict();