import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { printer_statusesOrderByWithRelationInputObjectSchema as printer_statusesOrderByWithRelationInputObjectSchema } from './objects/printer_statusesOrderByWithRelationInput.schema';
import { printer_statusesWhereInputObjectSchema as printer_statusesWhereInputObjectSchema } from './objects/printer_statusesWhereInput.schema';
import { printer_statusesWhereUniqueInputObjectSchema as printer_statusesWhereUniqueInputObjectSchema } from './objects/printer_statusesWhereUniqueInput.schema';
import { Printer_statusesCountAggregateInputObjectSchema as Printer_statusesCountAggregateInputObjectSchema } from './objects/Printer_statusesCountAggregateInput.schema';
import { Printer_statusesMinAggregateInputObjectSchema as Printer_statusesMinAggregateInputObjectSchema } from './objects/Printer_statusesMinAggregateInput.schema';
import { Printer_statusesMaxAggregateInputObjectSchema as Printer_statusesMaxAggregateInputObjectSchema } from './objects/Printer_statusesMaxAggregateInput.schema';
import { Printer_statusesAvgAggregateInputObjectSchema as Printer_statusesAvgAggregateInputObjectSchema } from './objects/Printer_statusesAvgAggregateInput.schema';
import { Printer_statusesSumAggregateInputObjectSchema as Printer_statusesSumAggregateInputObjectSchema } from './objects/Printer_statusesSumAggregateInput.schema';

export const printer_statusesAggregateSchema: z.ZodType<Prisma.Printer_statusesAggregateArgs> = z.object({ orderBy: z.union([printer_statusesOrderByWithRelationInputObjectSchema, printer_statusesOrderByWithRelationInputObjectSchema.array()]).optional(), where: printer_statusesWhereInputObjectSchema.optional(), cursor: printer_statusesWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Printer_statusesCountAggregateInputObjectSchema ]).optional(), _min: Printer_statusesMinAggregateInputObjectSchema.optional(), _max: Printer_statusesMaxAggregateInputObjectSchema.optional(), _avg: Printer_statusesAvgAggregateInputObjectSchema.optional(), _sum: Printer_statusesSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.Printer_statusesAggregateArgs>;

export const printer_statusesAggregateZodSchema = z.object({ orderBy: z.union([printer_statusesOrderByWithRelationInputObjectSchema, printer_statusesOrderByWithRelationInputObjectSchema.array()]).optional(), where: printer_statusesWhereInputObjectSchema.optional(), cursor: printer_statusesWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Printer_statusesCountAggregateInputObjectSchema ]).optional(), _min: Printer_statusesMinAggregateInputObjectSchema.optional(), _max: Printer_statusesMaxAggregateInputObjectSchema.optional(), _avg: Printer_statusesAvgAggregateInputObjectSchema.optional(), _sum: Printer_statusesSumAggregateInputObjectSchema.optional() }).strict();