import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { printer_statusesOrderByWithRelationInputObjectSchema as printer_statusesOrderByWithRelationInputObjectSchema } from './objects/printer_statusesOrderByWithRelationInput.schema';
import { printer_statusesWhereInputObjectSchema as printer_statusesWhereInputObjectSchema } from './objects/printer_statusesWhereInput.schema';
import { printer_statusesWhereUniqueInputObjectSchema as printer_statusesWhereUniqueInputObjectSchema } from './objects/printer_statusesWhereUniqueInput.schema';
import { Printer_statusesCountAggregateInputObjectSchema as Printer_statusesCountAggregateInputObjectSchema } from './objects/Printer_statusesCountAggregateInput.schema';

export const printer_statusesCountSchema: z.ZodType<Prisma.printer_statusesCountArgs> = z.object({ orderBy: z.union([printer_statusesOrderByWithRelationInputObjectSchema, printer_statusesOrderByWithRelationInputObjectSchema.array()]).optional(), where: printer_statusesWhereInputObjectSchema.optional(), cursor: printer_statusesWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), select: z.union([ z.literal(true), Printer_statusesCountAggregateInputObjectSchema ]).optional() }).strict() as unknown as z.ZodType<Prisma.printer_statusesCountArgs>;

export const printer_statusesCountZodSchema = z.object({ orderBy: z.union([printer_statusesOrderByWithRelationInputObjectSchema, printer_statusesOrderByWithRelationInputObjectSchema.array()]).optional(), where: printer_statusesWhereInputObjectSchema.optional(), cursor: printer_statusesWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), select: z.union([ z.literal(true), Printer_statusesCountAggregateInputObjectSchema ]).optional() }).strict();