import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { request_statusesOrderByWithRelationInputObjectSchema as request_statusesOrderByWithRelationInputObjectSchema } from './objects/request_statusesOrderByWithRelationInput.schema';
import { request_statusesWhereInputObjectSchema as request_statusesWhereInputObjectSchema } from './objects/request_statusesWhereInput.schema';
import { request_statusesWhereUniqueInputObjectSchema as request_statusesWhereUniqueInputObjectSchema } from './objects/request_statusesWhereUniqueInput.schema';
import { Request_statusesCountAggregateInputObjectSchema as Request_statusesCountAggregateInputObjectSchema } from './objects/Request_statusesCountAggregateInput.schema';

export const request_statusesCountSchema: z.ZodType<Prisma.request_statusesCountArgs> = z.object({ orderBy: z.union([request_statusesOrderByWithRelationInputObjectSchema, request_statusesOrderByWithRelationInputObjectSchema.array()]).optional(), where: request_statusesWhereInputObjectSchema.optional(), cursor: request_statusesWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), select: z.union([ z.literal(true), Request_statusesCountAggregateInputObjectSchema ]).optional() }).strict() as unknown as z.ZodType<Prisma.request_statusesCountArgs>;

export const request_statusesCountZodSchema = z.object({ orderBy: z.union([request_statusesOrderByWithRelationInputObjectSchema, request_statusesOrderByWithRelationInputObjectSchema.array()]).optional(), where: request_statusesWhereInputObjectSchema.optional(), cursor: request_statusesWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), select: z.union([ z.literal(true), Request_statusesCountAggregateInputObjectSchema ]).optional() }).strict();