import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { activity_logWhereInputObjectSchema as activity_logWhereInputObjectSchema } from './objects/activity_logWhereInput.schema';
import { activity_logOrderByWithAggregationInputObjectSchema as activity_logOrderByWithAggregationInputObjectSchema } from './objects/activity_logOrderByWithAggregationInput.schema';
import { activity_logScalarWhereWithAggregatesInputObjectSchema as activity_logScalarWhereWithAggregatesInputObjectSchema } from './objects/activity_logScalarWhereWithAggregatesInput.schema';
import { ActivityLogScalarFieldEnumSchema } from './enums/ActivityLogScalarFieldEnum.schema';
import { Activity_logCountAggregateInputObjectSchema as Activity_logCountAggregateInputObjectSchema } from './objects/Activity_logCountAggregateInput.schema';
import { Activity_logMinAggregateInputObjectSchema as Activity_logMinAggregateInputObjectSchema } from './objects/Activity_logMinAggregateInput.schema';
import { Activity_logMaxAggregateInputObjectSchema as Activity_logMaxAggregateInputObjectSchema } from './objects/Activity_logMaxAggregateInput.schema';
import { Activity_logAvgAggregateInputObjectSchema as Activity_logAvgAggregateInputObjectSchema } from './objects/Activity_logAvgAggregateInput.schema';
import { Activity_logSumAggregateInputObjectSchema as Activity_logSumAggregateInputObjectSchema } from './objects/Activity_logSumAggregateInput.schema';

export const activity_logGroupBySchema: z.ZodType<Prisma.activity_logGroupByArgs> = z.object({ where: activity_logWhereInputObjectSchema.optional(), orderBy: z.union([activity_logOrderByWithAggregationInputObjectSchema, activity_logOrderByWithAggregationInputObjectSchema.array()]).optional(), having: activity_logScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ActivityLogScalarFieldEnumSchema), _count: z.union([ z.literal(true), Activity_logCountAggregateInputObjectSchema ]).optional(), _min: Activity_logMinAggregateInputObjectSchema.optional(), _max: Activity_logMaxAggregateInputObjectSchema.optional(), _avg: Activity_logAvgAggregateInputObjectSchema.optional(), _sum: Activity_logSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.activity_logGroupByArgs>;

export const activity_logGroupByZodSchema = z.object({ where: activity_logWhereInputObjectSchema.optional(), orderBy: z.union([activity_logOrderByWithAggregationInputObjectSchema, activity_logOrderByWithAggregationInputObjectSchema.array()]).optional(), having: activity_logScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ActivityLogScalarFieldEnumSchema), _count: z.union([ z.literal(true), Activity_logCountAggregateInputObjectSchema ]).optional(), _min: Activity_logMinAggregateInputObjectSchema.optional(), _max: Activity_logMaxAggregateInputObjectSchema.optional(), _avg: Activity_logAvgAggregateInputObjectSchema.optional(), _sum: Activity_logSumAggregateInputObjectSchema.optional() }).strict();