import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ordersWhereInputObjectSchema as ordersWhereInputObjectSchema } from './objects/ordersWhereInput.schema';
import { ordersOrderByWithAggregationInputObjectSchema as ordersOrderByWithAggregationInputObjectSchema } from './objects/ordersOrderByWithAggregationInput.schema';
import { ordersScalarWhereWithAggregatesInputObjectSchema as ordersScalarWhereWithAggregatesInputObjectSchema } from './objects/ordersScalarWhereWithAggregatesInput.schema';
import { OrdersScalarFieldEnumSchema } from './enums/OrdersScalarFieldEnum.schema';
import { OrdersCountAggregateInputObjectSchema as OrdersCountAggregateInputObjectSchema } from './objects/OrdersCountAggregateInput.schema';
import { OrdersMinAggregateInputObjectSchema as OrdersMinAggregateInputObjectSchema } from './objects/OrdersMinAggregateInput.schema';
import { OrdersMaxAggregateInputObjectSchema as OrdersMaxAggregateInputObjectSchema } from './objects/OrdersMaxAggregateInput.schema';
import { OrdersAvgAggregateInputObjectSchema as OrdersAvgAggregateInputObjectSchema } from './objects/OrdersAvgAggregateInput.schema';
import { OrdersSumAggregateInputObjectSchema as OrdersSumAggregateInputObjectSchema } from './objects/OrdersSumAggregateInput.schema';

export const ordersGroupBySchema: z.ZodType<Prisma.ordersGroupByArgs> = z.object({ where: ordersWhereInputObjectSchema.optional(), orderBy: z.union([ordersOrderByWithAggregationInputObjectSchema, ordersOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ordersScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(OrdersScalarFieldEnumSchema), _count: z.union([ z.literal(true), OrdersCountAggregateInputObjectSchema ]).optional(), _min: OrdersMinAggregateInputObjectSchema.optional(), _max: OrdersMaxAggregateInputObjectSchema.optional(), _avg: OrdersAvgAggregateInputObjectSchema.optional(), _sum: OrdersSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ordersGroupByArgs>;

export const ordersGroupByZodSchema = z.object({ where: ordersWhereInputObjectSchema.optional(), orderBy: z.union([ordersOrderByWithAggregationInputObjectSchema, ordersOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ordersScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(OrdersScalarFieldEnumSchema), _count: z.union([ z.literal(true), OrdersCountAggregateInputObjectSchema ]).optional(), _min: OrdersMinAggregateInputObjectSchema.optional(), _max: OrdersMaxAggregateInputObjectSchema.optional(), _avg: OrdersAvgAggregateInputObjectSchema.optional(), _sum: OrdersSumAggregateInputObjectSchema.optional() }).strict();