import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { recycling_logWhereInputObjectSchema as recycling_logWhereInputObjectSchema } from './objects/recycling_logWhereInput.schema';
import { recycling_logOrderByWithAggregationInputObjectSchema as recycling_logOrderByWithAggregationInputObjectSchema } from './objects/recycling_logOrderByWithAggregationInput.schema';
import { recycling_logScalarWhereWithAggregatesInputObjectSchema as recycling_logScalarWhereWithAggregatesInputObjectSchema } from './objects/recycling_logScalarWhereWithAggregatesInput.schema';
import { RecyclingLogScalarFieldEnumSchema } from './enums/RecyclingLogScalarFieldEnum.schema';
import { Recycling_logCountAggregateInputObjectSchema as Recycling_logCountAggregateInputObjectSchema } from './objects/Recycling_logCountAggregateInput.schema';
import { Recycling_logMinAggregateInputObjectSchema as Recycling_logMinAggregateInputObjectSchema } from './objects/Recycling_logMinAggregateInput.schema';
import { Recycling_logMaxAggregateInputObjectSchema as Recycling_logMaxAggregateInputObjectSchema } from './objects/Recycling_logMaxAggregateInput.schema';
import { Recycling_logAvgAggregateInputObjectSchema as Recycling_logAvgAggregateInputObjectSchema } from './objects/Recycling_logAvgAggregateInput.schema';
import { Recycling_logSumAggregateInputObjectSchema as Recycling_logSumAggregateInputObjectSchema } from './objects/Recycling_logSumAggregateInput.schema';

export const recycling_logGroupBySchema: z.ZodType<Prisma.recycling_logGroupByArgs> = z.object({ where: recycling_logWhereInputObjectSchema.optional(), orderBy: z.union([recycling_logOrderByWithAggregationInputObjectSchema, recycling_logOrderByWithAggregationInputObjectSchema.array()]).optional(), having: recycling_logScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(RecyclingLogScalarFieldEnumSchema), _count: z.union([ z.literal(true), Recycling_logCountAggregateInputObjectSchema ]).optional(), _min: Recycling_logMinAggregateInputObjectSchema.optional(), _max: Recycling_logMaxAggregateInputObjectSchema.optional(), _avg: Recycling_logAvgAggregateInputObjectSchema.optional(), _sum: Recycling_logSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.recycling_logGroupByArgs>;

export const recycling_logGroupByZodSchema = z.object({ where: recycling_logWhereInputObjectSchema.optional(), orderBy: z.union([recycling_logOrderByWithAggregationInputObjectSchema, recycling_logOrderByWithAggregationInputObjectSchema.array()]).optional(), having: recycling_logScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(RecyclingLogScalarFieldEnumSchema), _count: z.union([ z.literal(true), Recycling_logCountAggregateInputObjectSchema ]).optional(), _min: Recycling_logMinAggregateInputObjectSchema.optional(), _max: Recycling_logMaxAggregateInputObjectSchema.optional(), _avg: Recycling_logAvgAggregateInputObjectSchema.optional(), _sum: Recycling_logSumAggregateInputObjectSchema.optional() }).strict();