import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { shop_sectionsWhereInputObjectSchema as shop_sectionsWhereInputObjectSchema } from './objects/shop_sectionsWhereInput.schema';
import { shop_sectionsOrderByWithAggregationInputObjectSchema as shop_sectionsOrderByWithAggregationInputObjectSchema } from './objects/shop_sectionsOrderByWithAggregationInput.schema';
import { shop_sectionsScalarWhereWithAggregatesInputObjectSchema as shop_sectionsScalarWhereWithAggregatesInputObjectSchema } from './objects/shop_sectionsScalarWhereWithAggregatesInput.schema';
import { ShopSectionsScalarFieldEnumSchema } from './enums/ShopSectionsScalarFieldEnum.schema';
import { Shop_sectionsCountAggregateInputObjectSchema as Shop_sectionsCountAggregateInputObjectSchema } from './objects/Shop_sectionsCountAggregateInput.schema';
import { Shop_sectionsMinAggregateInputObjectSchema as Shop_sectionsMinAggregateInputObjectSchema } from './objects/Shop_sectionsMinAggregateInput.schema';
import { Shop_sectionsMaxAggregateInputObjectSchema as Shop_sectionsMaxAggregateInputObjectSchema } from './objects/Shop_sectionsMaxAggregateInput.schema';
import { Shop_sectionsAvgAggregateInputObjectSchema as Shop_sectionsAvgAggregateInputObjectSchema } from './objects/Shop_sectionsAvgAggregateInput.schema';
import { Shop_sectionsSumAggregateInputObjectSchema as Shop_sectionsSumAggregateInputObjectSchema } from './objects/Shop_sectionsSumAggregateInput.schema';

export const shop_sectionsGroupBySchema: z.ZodType<Prisma.shop_sectionsGroupByArgs> = z.object({ where: shop_sectionsWhereInputObjectSchema.optional(), orderBy: z.union([shop_sectionsOrderByWithAggregationInputObjectSchema, shop_sectionsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: shop_sectionsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ShopSectionsScalarFieldEnumSchema), _count: z.union([ z.literal(true), Shop_sectionsCountAggregateInputObjectSchema ]).optional(), _min: Shop_sectionsMinAggregateInputObjectSchema.optional(), _max: Shop_sectionsMaxAggregateInputObjectSchema.optional(), _avg: Shop_sectionsAvgAggregateInputObjectSchema.optional(), _sum: Shop_sectionsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.shop_sectionsGroupByArgs>;

export const shop_sectionsGroupByZodSchema = z.object({ where: shop_sectionsWhereInputObjectSchema.optional(), orderBy: z.union([shop_sectionsOrderByWithAggregationInputObjectSchema, shop_sectionsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: shop_sectionsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ShopSectionsScalarFieldEnumSchema), _count: z.union([ z.literal(true), Shop_sectionsCountAggregateInputObjectSchema ]).optional(), _min: Shop_sectionsMinAggregateInputObjectSchema.optional(), _max: Shop_sectionsMaxAggregateInputObjectSchema.optional(), _avg: Shop_sectionsAvgAggregateInputObjectSchema.optional(), _sum: Shop_sectionsSumAggregateInputObjectSchema.optional() }).strict();