import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { printer_statusesWhereInputObjectSchema as printer_statusesWhereInputObjectSchema } from './objects/printer_statusesWhereInput.schema';
import { printer_statusesOrderByWithAggregationInputObjectSchema as printer_statusesOrderByWithAggregationInputObjectSchema } from './objects/printer_statusesOrderByWithAggregationInput.schema';
import { printer_statusesScalarWhereWithAggregatesInputObjectSchema as printer_statusesScalarWhereWithAggregatesInputObjectSchema } from './objects/printer_statusesScalarWhereWithAggregatesInput.schema';
import { PrinterStatusesScalarFieldEnumSchema } from './enums/PrinterStatusesScalarFieldEnum.schema';
import { Printer_statusesCountAggregateInputObjectSchema as Printer_statusesCountAggregateInputObjectSchema } from './objects/Printer_statusesCountAggregateInput.schema';
import { Printer_statusesMinAggregateInputObjectSchema as Printer_statusesMinAggregateInputObjectSchema } from './objects/Printer_statusesMinAggregateInput.schema';
import { Printer_statusesMaxAggregateInputObjectSchema as Printer_statusesMaxAggregateInputObjectSchema } from './objects/Printer_statusesMaxAggregateInput.schema';
import { Printer_statusesAvgAggregateInputObjectSchema as Printer_statusesAvgAggregateInputObjectSchema } from './objects/Printer_statusesAvgAggregateInput.schema';
import { Printer_statusesSumAggregateInputObjectSchema as Printer_statusesSumAggregateInputObjectSchema } from './objects/Printer_statusesSumAggregateInput.schema';

export const printer_statusesGroupBySchema: z.ZodType<Prisma.printer_statusesGroupByArgs> = z.object({ where: printer_statusesWhereInputObjectSchema.optional(), orderBy: z.union([printer_statusesOrderByWithAggregationInputObjectSchema, printer_statusesOrderByWithAggregationInputObjectSchema.array()]).optional(), having: printer_statusesScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(PrinterStatusesScalarFieldEnumSchema), _count: z.union([ z.literal(true), Printer_statusesCountAggregateInputObjectSchema ]).optional(), _min: Printer_statusesMinAggregateInputObjectSchema.optional(), _max: Printer_statusesMaxAggregateInputObjectSchema.optional(), _avg: Printer_statusesAvgAggregateInputObjectSchema.optional(), _sum: Printer_statusesSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.printer_statusesGroupByArgs>;

export const printer_statusesGroupByZodSchema = z.object({ where: printer_statusesWhereInputObjectSchema.optional(), orderBy: z.union([printer_statusesOrderByWithAggregationInputObjectSchema, printer_statusesOrderByWithAggregationInputObjectSchema.array()]).optional(), having: printer_statusesScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(PrinterStatusesScalarFieldEnumSchema), _count: z.union([ z.literal(true), Printer_statusesCountAggregateInputObjectSchema ]).optional(), _min: Printer_statusesMinAggregateInputObjectSchema.optional(), _max: Printer_statusesMaxAggregateInputObjectSchema.optional(), _avg: Printer_statusesAvgAggregateInputObjectSchema.optional(), _sum: Printer_statusesSumAggregateInputObjectSchema.optional() }).strict();