import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { process_instance_stepsWhereInputObjectSchema as process_instance_stepsWhereInputObjectSchema } from './objects/process_instance_stepsWhereInput.schema';
import { process_instance_stepsOrderByWithAggregationInputObjectSchema as process_instance_stepsOrderByWithAggregationInputObjectSchema } from './objects/process_instance_stepsOrderByWithAggregationInput.schema';
import { process_instance_stepsScalarWhereWithAggregatesInputObjectSchema as process_instance_stepsScalarWhereWithAggregatesInputObjectSchema } from './objects/process_instance_stepsScalarWhereWithAggregatesInput.schema';
import { ProcessInstanceStepsScalarFieldEnumSchema } from './enums/ProcessInstanceStepsScalarFieldEnum.schema';
import { Process_instance_stepsCountAggregateInputObjectSchema as Process_instance_stepsCountAggregateInputObjectSchema } from './objects/Process_instance_stepsCountAggregateInput.schema';
import { Process_instance_stepsMinAggregateInputObjectSchema as Process_instance_stepsMinAggregateInputObjectSchema } from './objects/Process_instance_stepsMinAggregateInput.schema';
import { Process_instance_stepsMaxAggregateInputObjectSchema as Process_instance_stepsMaxAggregateInputObjectSchema } from './objects/Process_instance_stepsMaxAggregateInput.schema';
import { Process_instance_stepsAvgAggregateInputObjectSchema as Process_instance_stepsAvgAggregateInputObjectSchema } from './objects/Process_instance_stepsAvgAggregateInput.schema';
import { Process_instance_stepsSumAggregateInputObjectSchema as Process_instance_stepsSumAggregateInputObjectSchema } from './objects/Process_instance_stepsSumAggregateInput.schema';

export const process_instance_stepsGroupBySchema: z.ZodType<Prisma.process_instance_stepsGroupByArgs> = z.object({ where: process_instance_stepsWhereInputObjectSchema.optional(), orderBy: z.union([process_instance_stepsOrderByWithAggregationInputObjectSchema, process_instance_stepsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: process_instance_stepsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ProcessInstanceStepsScalarFieldEnumSchema), _count: z.union([ z.literal(true), Process_instance_stepsCountAggregateInputObjectSchema ]).optional(), _min: Process_instance_stepsMinAggregateInputObjectSchema.optional(), _max: Process_instance_stepsMaxAggregateInputObjectSchema.optional(), _avg: Process_instance_stepsAvgAggregateInputObjectSchema.optional(), _sum: Process_instance_stepsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.process_instance_stepsGroupByArgs>;

export const process_instance_stepsGroupByZodSchema = z.object({ where: process_instance_stepsWhereInputObjectSchema.optional(), orderBy: z.union([process_instance_stepsOrderByWithAggregationInputObjectSchema, process_instance_stepsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: process_instance_stepsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ProcessInstanceStepsScalarFieldEnumSchema), _count: z.union([ z.literal(true), Process_instance_stepsCountAggregateInputObjectSchema ]).optional(), _min: Process_instance_stepsMinAggregateInputObjectSchema.optional(), _max: Process_instance_stepsMaxAggregateInputObjectSchema.optional(), _avg: Process_instance_stepsAvgAggregateInputObjectSchema.optional(), _sum: Process_instance_stepsSumAggregateInputObjectSchema.optional() }).strict();