import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { product_variantsWhereInputObjectSchema as product_variantsWhereInputObjectSchema } from './objects/product_variantsWhereInput.schema';
import { product_variantsOrderByWithAggregationInputObjectSchema as product_variantsOrderByWithAggregationInputObjectSchema } from './objects/product_variantsOrderByWithAggregationInput.schema';
import { product_variantsScalarWhereWithAggregatesInputObjectSchema as product_variantsScalarWhereWithAggregatesInputObjectSchema } from './objects/product_variantsScalarWhereWithAggregatesInput.schema';
import { ProductVariantsScalarFieldEnumSchema } from './enums/ProductVariantsScalarFieldEnum.schema';
import { Product_variantsCountAggregateInputObjectSchema as Product_variantsCountAggregateInputObjectSchema } from './objects/Product_variantsCountAggregateInput.schema';
import { Product_variantsMinAggregateInputObjectSchema as Product_variantsMinAggregateInputObjectSchema } from './objects/Product_variantsMinAggregateInput.schema';
import { Product_variantsMaxAggregateInputObjectSchema as Product_variantsMaxAggregateInputObjectSchema } from './objects/Product_variantsMaxAggregateInput.schema';
import { Product_variantsAvgAggregateInputObjectSchema as Product_variantsAvgAggregateInputObjectSchema } from './objects/Product_variantsAvgAggregateInput.schema';
import { Product_variantsSumAggregateInputObjectSchema as Product_variantsSumAggregateInputObjectSchema } from './objects/Product_variantsSumAggregateInput.schema';

export const product_variantsGroupBySchema: z.ZodType<Prisma.product_variantsGroupByArgs> = z.object({ where: product_variantsWhereInputObjectSchema.optional(), orderBy: z.union([product_variantsOrderByWithAggregationInputObjectSchema, product_variantsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: product_variantsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ProductVariantsScalarFieldEnumSchema), _count: z.union([ z.literal(true), Product_variantsCountAggregateInputObjectSchema ]).optional(), _min: Product_variantsMinAggregateInputObjectSchema.optional(), _max: Product_variantsMaxAggregateInputObjectSchema.optional(), _avg: Product_variantsAvgAggregateInputObjectSchema.optional(), _sum: Product_variantsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.product_variantsGroupByArgs>;

export const product_variantsGroupByZodSchema = z.object({ where: product_variantsWhereInputObjectSchema.optional(), orderBy: z.union([product_variantsOrderByWithAggregationInputObjectSchema, product_variantsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: product_variantsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ProductVariantsScalarFieldEnumSchema), _count: z.union([ z.literal(true), Product_variantsCountAggregateInputObjectSchema ]).optional(), _min: Product_variantsMinAggregateInputObjectSchema.optional(), _max: Product_variantsMaxAggregateInputObjectSchema.optional(), _avg: Product_variantsAvgAggregateInputObjectSchema.optional(), _sum: Product_variantsSumAggregateInputObjectSchema.optional() }).strict();