import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { gradesWhereInputObjectSchema as gradesWhereInputObjectSchema } from './objects/gradesWhereInput.schema';
import { gradesOrderByWithAggregationInputObjectSchema as gradesOrderByWithAggregationInputObjectSchema } from './objects/gradesOrderByWithAggregationInput.schema';
import { gradesScalarWhereWithAggregatesInputObjectSchema as gradesScalarWhereWithAggregatesInputObjectSchema } from './objects/gradesScalarWhereWithAggregatesInput.schema';
import { GradesScalarFieldEnumSchema } from './enums/GradesScalarFieldEnum.schema';
import { GradesCountAggregateInputObjectSchema as GradesCountAggregateInputObjectSchema } from './objects/GradesCountAggregateInput.schema';
import { GradesMinAggregateInputObjectSchema as GradesMinAggregateInputObjectSchema } from './objects/GradesMinAggregateInput.schema';
import { GradesMaxAggregateInputObjectSchema as GradesMaxAggregateInputObjectSchema } from './objects/GradesMaxAggregateInput.schema';
import { GradesAvgAggregateInputObjectSchema as GradesAvgAggregateInputObjectSchema } from './objects/GradesAvgAggregateInput.schema';
import { GradesSumAggregateInputObjectSchema as GradesSumAggregateInputObjectSchema } from './objects/GradesSumAggregateInput.schema';

export const gradesGroupBySchema: z.ZodType<Prisma.gradesGroupByArgs> = z.object({ where: gradesWhereInputObjectSchema.optional(), orderBy: z.union([gradesOrderByWithAggregationInputObjectSchema, gradesOrderByWithAggregationInputObjectSchema.array()]).optional(), having: gradesScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(GradesScalarFieldEnumSchema), _count: z.union([ z.literal(true), GradesCountAggregateInputObjectSchema ]).optional(), _min: GradesMinAggregateInputObjectSchema.optional(), _max: GradesMaxAggregateInputObjectSchema.optional(), _avg: GradesAvgAggregateInputObjectSchema.optional(), _sum: GradesSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.gradesGroupByArgs>;

export const gradesGroupByZodSchema = z.object({ where: gradesWhereInputObjectSchema.optional(), orderBy: z.union([gradesOrderByWithAggregationInputObjectSchema, gradesOrderByWithAggregationInputObjectSchema.array()]).optional(), having: gradesScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(GradesScalarFieldEnumSchema), _count: z.union([ z.literal(true), GradesCountAggregateInputObjectSchema ]).optional(), _min: GradesMinAggregateInputObjectSchema.optional(), _max: GradesMaxAggregateInputObjectSchema.optional(), _avg: GradesAvgAggregateInputObjectSchema.optional(), _sum: GradesSumAggregateInputObjectSchema.optional() }).strict();