import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { requestsWhereInputObjectSchema as requestsWhereInputObjectSchema } from './objects/requestsWhereInput.schema';
import { requestsOrderByWithAggregationInputObjectSchema as requestsOrderByWithAggregationInputObjectSchema } from './objects/requestsOrderByWithAggregationInput.schema';
import { requestsScalarWhereWithAggregatesInputObjectSchema as requestsScalarWhereWithAggregatesInputObjectSchema } from './objects/requestsScalarWhereWithAggregatesInput.schema';
import { RequestsScalarFieldEnumSchema } from './enums/RequestsScalarFieldEnum.schema';
import { RequestsCountAggregateInputObjectSchema as RequestsCountAggregateInputObjectSchema } from './objects/RequestsCountAggregateInput.schema';
import { RequestsMinAggregateInputObjectSchema as RequestsMinAggregateInputObjectSchema } from './objects/RequestsMinAggregateInput.schema';
import { RequestsMaxAggregateInputObjectSchema as RequestsMaxAggregateInputObjectSchema } from './objects/RequestsMaxAggregateInput.schema';
import { RequestsAvgAggregateInputObjectSchema as RequestsAvgAggregateInputObjectSchema } from './objects/RequestsAvgAggregateInput.schema';
import { RequestsSumAggregateInputObjectSchema as RequestsSumAggregateInputObjectSchema } from './objects/RequestsSumAggregateInput.schema';

export const requestsGroupBySchema: z.ZodType<Prisma.requestsGroupByArgs> = z.object({ where: requestsWhereInputObjectSchema.optional(), orderBy: z.union([requestsOrderByWithAggregationInputObjectSchema, requestsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: requestsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(RequestsScalarFieldEnumSchema), _count: z.union([ z.literal(true), RequestsCountAggregateInputObjectSchema ]).optional(), _min: RequestsMinAggregateInputObjectSchema.optional(), _max: RequestsMaxAggregateInputObjectSchema.optional(), _avg: RequestsAvgAggregateInputObjectSchema.optional(), _sum: RequestsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.requestsGroupByArgs>;

export const requestsGroupByZodSchema = z.object({ where: requestsWhereInputObjectSchema.optional(), orderBy: z.union([requestsOrderByWithAggregationInputObjectSchema, requestsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: requestsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(RequestsScalarFieldEnumSchema), _count: z.union([ z.literal(true), RequestsCountAggregateInputObjectSchema ]).optional(), _min: RequestsMinAggregateInputObjectSchema.optional(), _max: RequestsMaxAggregateInputObjectSchema.optional(), _avg: RequestsAvgAggregateInputObjectSchema.optional(), _sum: RequestsSumAggregateInputObjectSchema.optional() }).strict();