import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { process_templatesWhereInputObjectSchema as process_templatesWhereInputObjectSchema } from './objects/process_templatesWhereInput.schema';
import { process_templatesOrderByWithAggregationInputObjectSchema as process_templatesOrderByWithAggregationInputObjectSchema } from './objects/process_templatesOrderByWithAggregationInput.schema';
import { process_templatesScalarWhereWithAggregatesInputObjectSchema as process_templatesScalarWhereWithAggregatesInputObjectSchema } from './objects/process_templatesScalarWhereWithAggregatesInput.schema';
import { ProcessTemplatesScalarFieldEnumSchema } from './enums/ProcessTemplatesScalarFieldEnum.schema';
import { Process_templatesCountAggregateInputObjectSchema as Process_templatesCountAggregateInputObjectSchema } from './objects/Process_templatesCountAggregateInput.schema';
import { Process_templatesMinAggregateInputObjectSchema as Process_templatesMinAggregateInputObjectSchema } from './objects/Process_templatesMinAggregateInput.schema';
import { Process_templatesMaxAggregateInputObjectSchema as Process_templatesMaxAggregateInputObjectSchema } from './objects/Process_templatesMaxAggregateInput.schema';
import { Process_templatesAvgAggregateInputObjectSchema as Process_templatesAvgAggregateInputObjectSchema } from './objects/Process_templatesAvgAggregateInput.schema';
import { Process_templatesSumAggregateInputObjectSchema as Process_templatesSumAggregateInputObjectSchema } from './objects/Process_templatesSumAggregateInput.schema';

export const process_templatesGroupBySchema: z.ZodType<Prisma.process_templatesGroupByArgs> = z.object({ where: process_templatesWhereInputObjectSchema.optional(), orderBy: z.union([process_templatesOrderByWithAggregationInputObjectSchema, process_templatesOrderByWithAggregationInputObjectSchema.array()]).optional(), having: process_templatesScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ProcessTemplatesScalarFieldEnumSchema), _count: z.union([ z.literal(true), Process_templatesCountAggregateInputObjectSchema ]).optional(), _min: Process_templatesMinAggregateInputObjectSchema.optional(), _max: Process_templatesMaxAggregateInputObjectSchema.optional(), _avg: Process_templatesAvgAggregateInputObjectSchema.optional(), _sum: Process_templatesSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.process_templatesGroupByArgs>;

export const process_templatesGroupByZodSchema = z.object({ where: process_templatesWhereInputObjectSchema.optional(), orderBy: z.union([process_templatesOrderByWithAggregationInputObjectSchema, process_templatesOrderByWithAggregationInputObjectSchema.array()]).optional(), having: process_templatesScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ProcessTemplatesScalarFieldEnumSchema), _count: z.union([ z.literal(true), Process_templatesCountAggregateInputObjectSchema ]).optional(), _min: Process_templatesMinAggregateInputObjectSchema.optional(), _max: Process_templatesMaxAggregateInputObjectSchema.optional(), _avg: Process_templatesAvgAggregateInputObjectSchema.optional(), _sum: Process_templatesSumAggregateInputObjectSchema.optional() }).strict();