import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { process_instancesWhereInputObjectSchema as process_instancesWhereInputObjectSchema } from './objects/process_instancesWhereInput.schema';
import { process_instancesOrderByWithAggregationInputObjectSchema as process_instancesOrderByWithAggregationInputObjectSchema } from './objects/process_instancesOrderByWithAggregationInput.schema';
import { process_instancesScalarWhereWithAggregatesInputObjectSchema as process_instancesScalarWhereWithAggregatesInputObjectSchema } from './objects/process_instancesScalarWhereWithAggregatesInput.schema';
import { ProcessInstancesScalarFieldEnumSchema } from './enums/ProcessInstancesScalarFieldEnum.schema';
import { Process_instancesCountAggregateInputObjectSchema as Process_instancesCountAggregateInputObjectSchema } from './objects/Process_instancesCountAggregateInput.schema';
import { Process_instancesMinAggregateInputObjectSchema as Process_instancesMinAggregateInputObjectSchema } from './objects/Process_instancesMinAggregateInput.schema';
import { Process_instancesMaxAggregateInputObjectSchema as Process_instancesMaxAggregateInputObjectSchema } from './objects/Process_instancesMaxAggregateInput.schema';
import { Process_instancesAvgAggregateInputObjectSchema as Process_instancesAvgAggregateInputObjectSchema } from './objects/Process_instancesAvgAggregateInput.schema';
import { Process_instancesSumAggregateInputObjectSchema as Process_instancesSumAggregateInputObjectSchema } from './objects/Process_instancesSumAggregateInput.schema';

export const process_instancesGroupBySchema: z.ZodType<Prisma.process_instancesGroupByArgs> = z.object({ where: process_instancesWhereInputObjectSchema.optional(), orderBy: z.union([process_instancesOrderByWithAggregationInputObjectSchema, process_instancesOrderByWithAggregationInputObjectSchema.array()]).optional(), having: process_instancesScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ProcessInstancesScalarFieldEnumSchema), _count: z.union([ z.literal(true), Process_instancesCountAggregateInputObjectSchema ]).optional(), _min: Process_instancesMinAggregateInputObjectSchema.optional(), _max: Process_instancesMaxAggregateInputObjectSchema.optional(), _avg: Process_instancesAvgAggregateInputObjectSchema.optional(), _sum: Process_instancesSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.process_instancesGroupByArgs>;

export const process_instancesGroupByZodSchema = z.object({ where: process_instancesWhereInputObjectSchema.optional(), orderBy: z.union([process_instancesOrderByWithAggregationInputObjectSchema, process_instancesOrderByWithAggregationInputObjectSchema.array()]).optional(), having: process_instancesScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ProcessInstancesScalarFieldEnumSchema), _count: z.union([ z.literal(true), Process_instancesCountAggregateInputObjectSchema ]).optional(), _min: Process_instancesMinAggregateInputObjectSchema.optional(), _max: Process_instancesMaxAggregateInputObjectSchema.optional(), _avg: Process_instancesAvgAggregateInputObjectSchema.optional(), _sum: Process_instancesSumAggregateInputObjectSchema.optional() }).strict();