import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { migrationsWhereInputObjectSchema as migrationsWhereInputObjectSchema } from './objects/migrationsWhereInput.schema';
import { migrationsOrderByWithAggregationInputObjectSchema as migrationsOrderByWithAggregationInputObjectSchema } from './objects/migrationsOrderByWithAggregationInput.schema';
import { migrationsScalarWhereWithAggregatesInputObjectSchema as migrationsScalarWhereWithAggregatesInputObjectSchema } from './objects/migrationsScalarWhereWithAggregatesInput.schema';
import { MigrationsScalarFieldEnumSchema } from './enums/MigrationsScalarFieldEnum.schema';
import { MigrationsCountAggregateInputObjectSchema as MigrationsCountAggregateInputObjectSchema } from './objects/MigrationsCountAggregateInput.schema';
import { MigrationsMinAggregateInputObjectSchema as MigrationsMinAggregateInputObjectSchema } from './objects/MigrationsMinAggregateInput.schema';
import { MigrationsMaxAggregateInputObjectSchema as MigrationsMaxAggregateInputObjectSchema } from './objects/MigrationsMaxAggregateInput.schema';
import { MigrationsAvgAggregateInputObjectSchema as MigrationsAvgAggregateInputObjectSchema } from './objects/MigrationsAvgAggregateInput.schema';
import { MigrationsSumAggregateInputObjectSchema as MigrationsSumAggregateInputObjectSchema } from './objects/MigrationsSumAggregateInput.schema';

export const migrationsGroupBySchema: z.ZodType<Prisma.migrationsGroupByArgs> = z.object({ where: migrationsWhereInputObjectSchema.optional(), orderBy: z.union([migrationsOrderByWithAggregationInputObjectSchema, migrationsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: migrationsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(MigrationsScalarFieldEnumSchema), _count: z.union([ z.literal(true), MigrationsCountAggregateInputObjectSchema ]).optional(), _min: MigrationsMinAggregateInputObjectSchema.optional(), _max: MigrationsMaxAggregateInputObjectSchema.optional(), _avg: MigrationsAvgAggregateInputObjectSchema.optional(), _sum: MigrationsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.migrationsGroupByArgs>;

export const migrationsGroupByZodSchema = z.object({ where: migrationsWhereInputObjectSchema.optional(), orderBy: z.union([migrationsOrderByWithAggregationInputObjectSchema, migrationsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: migrationsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(MigrationsScalarFieldEnumSchema), _count: z.union([ z.literal(true), MigrationsCountAggregateInputObjectSchema ]).optional(), _min: MigrationsMinAggregateInputObjectSchema.optional(), _max: MigrationsMaxAggregateInputObjectSchema.optional(), _avg: MigrationsAvgAggregateInputObjectSchema.optional(), _sum: MigrationsSumAggregateInputObjectSchema.optional() }).strict();