import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { process_template_stepsWhereInputObjectSchema as process_template_stepsWhereInputObjectSchema } from './objects/process_template_stepsWhereInput.schema';
import { process_template_stepsOrderByWithAggregationInputObjectSchema as process_template_stepsOrderByWithAggregationInputObjectSchema } from './objects/process_template_stepsOrderByWithAggregationInput.schema';
import { process_template_stepsScalarWhereWithAggregatesInputObjectSchema as process_template_stepsScalarWhereWithAggregatesInputObjectSchema } from './objects/process_template_stepsScalarWhereWithAggregatesInput.schema';
import { ProcessTemplateStepsScalarFieldEnumSchema } from './enums/ProcessTemplateStepsScalarFieldEnum.schema';
import { Process_template_stepsCountAggregateInputObjectSchema as Process_template_stepsCountAggregateInputObjectSchema } from './objects/Process_template_stepsCountAggregateInput.schema';
import { Process_template_stepsMinAggregateInputObjectSchema as Process_template_stepsMinAggregateInputObjectSchema } from './objects/Process_template_stepsMinAggregateInput.schema';
import { Process_template_stepsMaxAggregateInputObjectSchema as Process_template_stepsMaxAggregateInputObjectSchema } from './objects/Process_template_stepsMaxAggregateInput.schema';
import { Process_template_stepsAvgAggregateInputObjectSchema as Process_template_stepsAvgAggregateInputObjectSchema } from './objects/Process_template_stepsAvgAggregateInput.schema';
import { Process_template_stepsSumAggregateInputObjectSchema as Process_template_stepsSumAggregateInputObjectSchema } from './objects/Process_template_stepsSumAggregateInput.schema';

export const process_template_stepsGroupBySchema: z.ZodType<Prisma.process_template_stepsGroupByArgs> = z.object({ where: process_template_stepsWhereInputObjectSchema.optional(), orderBy: z.union([process_template_stepsOrderByWithAggregationInputObjectSchema, process_template_stepsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: process_template_stepsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ProcessTemplateStepsScalarFieldEnumSchema), _count: z.union([ z.literal(true), Process_template_stepsCountAggregateInputObjectSchema ]).optional(), _min: Process_template_stepsMinAggregateInputObjectSchema.optional(), _max: Process_template_stepsMaxAggregateInputObjectSchema.optional(), _avg: Process_template_stepsAvgAggregateInputObjectSchema.optional(), _sum: Process_template_stepsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.process_template_stepsGroupByArgs>;

export const process_template_stepsGroupByZodSchema = z.object({ where: process_template_stepsWhereInputObjectSchema.optional(), orderBy: z.union([process_template_stepsOrderByWithAggregationInputObjectSchema, process_template_stepsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: process_template_stepsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ProcessTemplateStepsScalarFieldEnumSchema), _count: z.union([ z.literal(true), Process_template_stepsCountAggregateInputObjectSchema ]).optional(), _min: Process_template_stepsMinAggregateInputObjectSchema.optional(), _max: Process_template_stepsMaxAggregateInputObjectSchema.optional(), _avg: Process_template_stepsAvgAggregateInputObjectSchema.optional(), _sum: Process_template_stepsSumAggregateInputObjectSchema.optional() }).strict();