import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { printersWhereInputObjectSchema as printersWhereInputObjectSchema } from './objects/printersWhereInput.schema';
import { printersOrderByWithAggregationInputObjectSchema as printersOrderByWithAggregationInputObjectSchema } from './objects/printersOrderByWithAggregationInput.schema';
import { printersScalarWhereWithAggregatesInputObjectSchema as printersScalarWhereWithAggregatesInputObjectSchema } from './objects/printersScalarWhereWithAggregatesInput.schema';
import { PrintersScalarFieldEnumSchema } from './enums/PrintersScalarFieldEnum.schema';
import { PrintersCountAggregateInputObjectSchema as PrintersCountAggregateInputObjectSchema } from './objects/PrintersCountAggregateInput.schema';
import { PrintersMinAggregateInputObjectSchema as PrintersMinAggregateInputObjectSchema } from './objects/PrintersMinAggregateInput.schema';
import { PrintersMaxAggregateInputObjectSchema as PrintersMaxAggregateInputObjectSchema } from './objects/PrintersMaxAggregateInput.schema';
import { PrintersAvgAggregateInputObjectSchema as PrintersAvgAggregateInputObjectSchema } from './objects/PrintersAvgAggregateInput.schema';
import { PrintersSumAggregateInputObjectSchema as PrintersSumAggregateInputObjectSchema } from './objects/PrintersSumAggregateInput.schema';

export const printersGroupBySchema: z.ZodType<Prisma.printersGroupByArgs> = z.object({ where: printersWhereInputObjectSchema.optional(), orderBy: z.union([printersOrderByWithAggregationInputObjectSchema, printersOrderByWithAggregationInputObjectSchema.array()]).optional(), having: printersScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(PrintersScalarFieldEnumSchema), _count: z.union([ z.literal(true), PrintersCountAggregateInputObjectSchema ]).optional(), _min: PrintersMinAggregateInputObjectSchema.optional(), _max: PrintersMaxAggregateInputObjectSchema.optional(), _avg: PrintersAvgAggregateInputObjectSchema.optional(), _sum: PrintersSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.printersGroupByArgs>;

export const printersGroupByZodSchema = z.object({ where: printersWhereInputObjectSchema.optional(), orderBy: z.union([printersOrderByWithAggregationInputObjectSchema, printersOrderByWithAggregationInputObjectSchema.array()]).optional(), having: printersScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(PrintersScalarFieldEnumSchema), _count: z.union([ z.literal(true), PrintersCountAggregateInputObjectSchema ]).optional(), _min: PrintersMinAggregateInputObjectSchema.optional(), _max: PrintersMaxAggregateInputObjectSchema.optional(), _avg: PrintersAvgAggregateInputObjectSchema.optional(), _sum: PrintersSumAggregateInputObjectSchema.optional() }).strict();