import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { step_actionsWhereInputObjectSchema as step_actionsWhereInputObjectSchema } from './objects/step_actionsWhereInput.schema';
import { step_actionsOrderByWithAggregationInputObjectSchema as step_actionsOrderByWithAggregationInputObjectSchema } from './objects/step_actionsOrderByWithAggregationInput.schema';
import { step_actionsScalarWhereWithAggregatesInputObjectSchema as step_actionsScalarWhereWithAggregatesInputObjectSchema } from './objects/step_actionsScalarWhereWithAggregatesInput.schema';
import { StepActionsScalarFieldEnumSchema } from './enums/StepActionsScalarFieldEnum.schema';
import { Step_actionsCountAggregateInputObjectSchema as Step_actionsCountAggregateInputObjectSchema } from './objects/Step_actionsCountAggregateInput.schema';
import { Step_actionsMinAggregateInputObjectSchema as Step_actionsMinAggregateInputObjectSchema } from './objects/Step_actionsMinAggregateInput.schema';
import { Step_actionsMaxAggregateInputObjectSchema as Step_actionsMaxAggregateInputObjectSchema } from './objects/Step_actionsMaxAggregateInput.schema';
import { Step_actionsAvgAggregateInputObjectSchema as Step_actionsAvgAggregateInputObjectSchema } from './objects/Step_actionsAvgAggregateInput.schema';
import { Step_actionsSumAggregateInputObjectSchema as Step_actionsSumAggregateInputObjectSchema } from './objects/Step_actionsSumAggregateInput.schema';

export const step_actionsGroupBySchema: z.ZodType<Prisma.step_actionsGroupByArgs> = z.object({ where: step_actionsWhereInputObjectSchema.optional(), orderBy: z.union([step_actionsOrderByWithAggregationInputObjectSchema, step_actionsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: step_actionsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(StepActionsScalarFieldEnumSchema), _count: z.union([ z.literal(true), Step_actionsCountAggregateInputObjectSchema ]).optional(), _min: Step_actionsMinAggregateInputObjectSchema.optional(), _max: Step_actionsMaxAggregateInputObjectSchema.optional(), _avg: Step_actionsAvgAggregateInputObjectSchema.optional(), _sum: Step_actionsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.step_actionsGroupByArgs>;

export const step_actionsGroupByZodSchema = z.object({ where: step_actionsWhereInputObjectSchema.optional(), orderBy: z.union([step_actionsOrderByWithAggregationInputObjectSchema, step_actionsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: step_actionsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(StepActionsScalarFieldEnumSchema), _count: z.union([ z.literal(true), Step_actionsCountAggregateInputObjectSchema ]).optional(), _min: Step_actionsMinAggregateInputObjectSchema.optional(), _max: Step_actionsMaxAggregateInputObjectSchema.optional(), _avg: Step_actionsAvgAggregateInputObjectSchema.optional(), _sum: Step_actionsSumAggregateInputObjectSchema.optional() }).strict();