import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { modelsWhereInputObjectSchema as modelsWhereInputObjectSchema } from './objects/modelsWhereInput.schema';
import { modelsOrderByWithAggregationInputObjectSchema as modelsOrderByWithAggregationInputObjectSchema } from './objects/modelsOrderByWithAggregationInput.schema';
import { modelsScalarWhereWithAggregatesInputObjectSchema as modelsScalarWhereWithAggregatesInputObjectSchema } from './objects/modelsScalarWhereWithAggregatesInput.schema';
import { ModelsScalarFieldEnumSchema } from './enums/ModelsScalarFieldEnum.schema';
import { ModelsCountAggregateInputObjectSchema as ModelsCountAggregateInputObjectSchema } from './objects/ModelsCountAggregateInput.schema';
import { ModelsMinAggregateInputObjectSchema as ModelsMinAggregateInputObjectSchema } from './objects/ModelsMinAggregateInput.schema';
import { ModelsMaxAggregateInputObjectSchema as ModelsMaxAggregateInputObjectSchema } from './objects/ModelsMaxAggregateInput.schema';
import { ModelsAvgAggregateInputObjectSchema as ModelsAvgAggregateInputObjectSchema } from './objects/ModelsAvgAggregateInput.schema';
import { ModelsSumAggregateInputObjectSchema as ModelsSumAggregateInputObjectSchema } from './objects/ModelsSumAggregateInput.schema';

export const modelsGroupBySchema: z.ZodType<Prisma.modelsGroupByArgs> = z.object({ where: modelsWhereInputObjectSchema.optional(), orderBy: z.union([modelsOrderByWithAggregationInputObjectSchema, modelsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: modelsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ModelsScalarFieldEnumSchema), _count: z.union([ z.literal(true), ModelsCountAggregateInputObjectSchema ]).optional(), _min: ModelsMinAggregateInputObjectSchema.optional(), _max: ModelsMaxAggregateInputObjectSchema.optional(), _avg: ModelsAvgAggregateInputObjectSchema.optional(), _sum: ModelsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.modelsGroupByArgs>;

export const modelsGroupByZodSchema = z.object({ where: modelsWhereInputObjectSchema.optional(), orderBy: z.union([modelsOrderByWithAggregationInputObjectSchema, modelsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: modelsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ModelsScalarFieldEnumSchema), _count: z.union([ z.literal(true), ModelsCountAggregateInputObjectSchema ]).optional(), _min: ModelsMinAggregateInputObjectSchema.optional(), _max: ModelsMaxAggregateInputObjectSchema.optional(), _avg: ModelsAvgAggregateInputObjectSchema.optional(), _sum: ModelsSumAggregateInputObjectSchema.optional() }).strict();