import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { eventsWhereInputObjectSchema as eventsWhereInputObjectSchema } from './objects/eventsWhereInput.schema';
import { eventsOrderByWithAggregationInputObjectSchema as eventsOrderByWithAggregationInputObjectSchema } from './objects/eventsOrderByWithAggregationInput.schema';
import { eventsScalarWhereWithAggregatesInputObjectSchema as eventsScalarWhereWithAggregatesInputObjectSchema } from './objects/eventsScalarWhereWithAggregatesInput.schema';
import { EventsScalarFieldEnumSchema } from './enums/EventsScalarFieldEnum.schema';
import { EventsCountAggregateInputObjectSchema as EventsCountAggregateInputObjectSchema } from './objects/EventsCountAggregateInput.schema';
import { EventsMinAggregateInputObjectSchema as EventsMinAggregateInputObjectSchema } from './objects/EventsMinAggregateInput.schema';
import { EventsMaxAggregateInputObjectSchema as EventsMaxAggregateInputObjectSchema } from './objects/EventsMaxAggregateInput.schema';
import { EventsAvgAggregateInputObjectSchema as EventsAvgAggregateInputObjectSchema } from './objects/EventsAvgAggregateInput.schema';
import { EventsSumAggregateInputObjectSchema as EventsSumAggregateInputObjectSchema } from './objects/EventsSumAggregateInput.schema';

export const eventsGroupBySchema: z.ZodType<Prisma.eventsGroupByArgs> = z.object({ where: eventsWhereInputObjectSchema.optional(), orderBy: z.union([eventsOrderByWithAggregationInputObjectSchema, eventsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: eventsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(EventsScalarFieldEnumSchema), _count: z.union([ z.literal(true), EventsCountAggregateInputObjectSchema ]).optional(), _min: EventsMinAggregateInputObjectSchema.optional(), _max: EventsMaxAggregateInputObjectSchema.optional(), _avg: EventsAvgAggregateInputObjectSchema.optional(), _sum: EventsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.eventsGroupByArgs>;

export const eventsGroupByZodSchema = z.object({ where: eventsWhereInputObjectSchema.optional(), orderBy: z.union([eventsOrderByWithAggregationInputObjectSchema, eventsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: eventsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(EventsScalarFieldEnumSchema), _count: z.union([ z.literal(true), EventsCountAggregateInputObjectSchema ]).optional(), _min: EventsMinAggregateInputObjectSchema.optional(), _max: EventsMaxAggregateInputObjectSchema.optional(), _avg: EventsAvgAggregateInputObjectSchema.optional(), _sum: EventsSumAggregateInputObjectSchema.optional() }).strict();