import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { step_contentWhereInputObjectSchema as step_contentWhereInputObjectSchema } from './objects/step_contentWhereInput.schema';
import { step_contentOrderByWithAggregationInputObjectSchema as step_contentOrderByWithAggregationInputObjectSchema } from './objects/step_contentOrderByWithAggregationInput.schema';
import { step_contentScalarWhereWithAggregatesInputObjectSchema as step_contentScalarWhereWithAggregatesInputObjectSchema } from './objects/step_contentScalarWhereWithAggregatesInput.schema';
import { StepContentScalarFieldEnumSchema } from './enums/StepContentScalarFieldEnum.schema';
import { Step_contentCountAggregateInputObjectSchema as Step_contentCountAggregateInputObjectSchema } from './objects/Step_contentCountAggregateInput.schema';
import { Step_contentMinAggregateInputObjectSchema as Step_contentMinAggregateInputObjectSchema } from './objects/Step_contentMinAggregateInput.schema';
import { Step_contentMaxAggregateInputObjectSchema as Step_contentMaxAggregateInputObjectSchema } from './objects/Step_contentMaxAggregateInput.schema';
import { Step_contentAvgAggregateInputObjectSchema as Step_contentAvgAggregateInputObjectSchema } from './objects/Step_contentAvgAggregateInput.schema';
import { Step_contentSumAggregateInputObjectSchema as Step_contentSumAggregateInputObjectSchema } from './objects/Step_contentSumAggregateInput.schema';

export const step_contentGroupBySchema: z.ZodType<Prisma.step_contentGroupByArgs> = z.object({ where: step_contentWhereInputObjectSchema.optional(), orderBy: z.union([step_contentOrderByWithAggregationInputObjectSchema, step_contentOrderByWithAggregationInputObjectSchema.array()]).optional(), having: step_contentScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(StepContentScalarFieldEnumSchema), _count: z.union([ z.literal(true), Step_contentCountAggregateInputObjectSchema ]).optional(), _min: Step_contentMinAggregateInputObjectSchema.optional(), _max: Step_contentMaxAggregateInputObjectSchema.optional(), _avg: Step_contentAvgAggregateInputObjectSchema.optional(), _sum: Step_contentSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.step_contentGroupByArgs>;

export const step_contentGroupByZodSchema = z.object({ where: step_contentWhereInputObjectSchema.optional(), orderBy: z.union([step_contentOrderByWithAggregationInputObjectSchema, step_contentOrderByWithAggregationInputObjectSchema.array()]).optional(), having: step_contentScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(StepContentScalarFieldEnumSchema), _count: z.union([ z.literal(true), Step_contentCountAggregateInputObjectSchema ]).optional(), _min: Step_contentMinAggregateInputObjectSchema.optional(), _max: Step_contentMaxAggregateInputObjectSchema.optional(), _avg: Step_contentAvgAggregateInputObjectSchema.optional(), _sum: Step_contentSumAggregateInputObjectSchema.optional() }).strict();