import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { activity_logsWhereInputObjectSchema as activity_logsWhereInputObjectSchema } from './objects/activity_logsWhereInput.schema';
import { activity_logsOrderByWithAggregationInputObjectSchema as activity_logsOrderByWithAggregationInputObjectSchema } from './objects/activity_logsOrderByWithAggregationInput.schema';
import { activity_logsScalarWhereWithAggregatesInputObjectSchema as activity_logsScalarWhereWithAggregatesInputObjectSchema } from './objects/activity_logsScalarWhereWithAggregatesInput.schema';
import { ActivityLogsScalarFieldEnumSchema } from './enums/ActivityLogsScalarFieldEnum.schema';
import { Activity_logsCountAggregateInputObjectSchema as Activity_logsCountAggregateInputObjectSchema } from './objects/Activity_logsCountAggregateInput.schema';
import { Activity_logsMinAggregateInputObjectSchema as Activity_logsMinAggregateInputObjectSchema } from './objects/Activity_logsMinAggregateInput.schema';
import { Activity_logsMaxAggregateInputObjectSchema as Activity_logsMaxAggregateInputObjectSchema } from './objects/Activity_logsMaxAggregateInput.schema';
import { Activity_logsAvgAggregateInputObjectSchema as Activity_logsAvgAggregateInputObjectSchema } from './objects/Activity_logsAvgAggregateInput.schema';
import { Activity_logsSumAggregateInputObjectSchema as Activity_logsSumAggregateInputObjectSchema } from './objects/Activity_logsSumAggregateInput.schema';

export const activity_logsGroupBySchema: z.ZodType<Prisma.activity_logsGroupByArgs> = z.object({ where: activity_logsWhereInputObjectSchema.optional(), orderBy: z.union([activity_logsOrderByWithAggregationInputObjectSchema, activity_logsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: activity_logsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ActivityLogsScalarFieldEnumSchema), _count: z.union([ z.literal(true), Activity_logsCountAggregateInputObjectSchema ]).optional(), _min: Activity_logsMinAggregateInputObjectSchema.optional(), _max: Activity_logsMaxAggregateInputObjectSchema.optional(), _avg: Activity_logsAvgAggregateInputObjectSchema.optional(), _sum: Activity_logsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.activity_logsGroupByArgs>;

export const activity_logsGroupByZodSchema = z.object({ where: activity_logsWhereInputObjectSchema.optional(), orderBy: z.union([activity_logsOrderByWithAggregationInputObjectSchema, activity_logsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: activity_logsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ActivityLogsScalarFieldEnumSchema), _count: z.union([ z.literal(true), Activity_logsCountAggregateInputObjectSchema ]).optional(), _min: Activity_logsMinAggregateInputObjectSchema.optional(), _max: Activity_logsMaxAggregateInputObjectSchema.optional(), _avg: Activity_logsAvgAggregateInputObjectSchema.optional(), _sum: Activity_logsSumAggregateInputObjectSchema.optional() }).strict();