import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { request_statusesWhereInputObjectSchema as request_statusesWhereInputObjectSchema } from './objects/request_statusesWhereInput.schema';
import { request_statusesOrderByWithAggregationInputObjectSchema as request_statusesOrderByWithAggregationInputObjectSchema } from './objects/request_statusesOrderByWithAggregationInput.schema';
import { request_statusesScalarWhereWithAggregatesInputObjectSchema as request_statusesScalarWhereWithAggregatesInputObjectSchema } from './objects/request_statusesScalarWhereWithAggregatesInput.schema';
import { RequestStatusesScalarFieldEnumSchema } from './enums/RequestStatusesScalarFieldEnum.schema';
import { Request_statusesCountAggregateInputObjectSchema as Request_statusesCountAggregateInputObjectSchema } from './objects/Request_statusesCountAggregateInput.schema';
import { Request_statusesMinAggregateInputObjectSchema as Request_statusesMinAggregateInputObjectSchema } from './objects/Request_statusesMinAggregateInput.schema';
import { Request_statusesMaxAggregateInputObjectSchema as Request_statusesMaxAggregateInputObjectSchema } from './objects/Request_statusesMaxAggregateInput.schema';
import { Request_statusesAvgAggregateInputObjectSchema as Request_statusesAvgAggregateInputObjectSchema } from './objects/Request_statusesAvgAggregateInput.schema';
import { Request_statusesSumAggregateInputObjectSchema as Request_statusesSumAggregateInputObjectSchema } from './objects/Request_statusesSumAggregateInput.schema';

export const request_statusesGroupBySchema: z.ZodType<Prisma.request_statusesGroupByArgs> = z.object({ where: request_statusesWhereInputObjectSchema.optional(), orderBy: z.union([request_statusesOrderByWithAggregationInputObjectSchema, request_statusesOrderByWithAggregationInputObjectSchema.array()]).optional(), having: request_statusesScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(RequestStatusesScalarFieldEnumSchema), _count: z.union([ z.literal(true), Request_statusesCountAggregateInputObjectSchema ]).optional(), _min: Request_statusesMinAggregateInputObjectSchema.optional(), _max: Request_statusesMaxAggregateInputObjectSchema.optional(), _avg: Request_statusesAvgAggregateInputObjectSchema.optional(), _sum: Request_statusesSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.request_statusesGroupByArgs>;

export const request_statusesGroupByZodSchema = z.object({ where: request_statusesWhereInputObjectSchema.optional(), orderBy: z.union([request_statusesOrderByWithAggregationInputObjectSchema, request_statusesOrderByWithAggregationInputObjectSchema.array()]).optional(), having: request_statusesScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(RequestStatusesScalarFieldEnumSchema), _count: z.union([ z.literal(true), Request_statusesCountAggregateInputObjectSchema ]).optional(), _min: Request_statusesMinAggregateInputObjectSchema.optional(), _max: Request_statusesMaxAggregateInputObjectSchema.optional(), _avg: Request_statusesAvgAggregateInputObjectSchema.optional(), _sum: Request_statusesSumAggregateInputObjectSchema.optional() }).strict();