import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { order_logsWhereInputObjectSchema as order_logsWhereInputObjectSchema } from './objects/order_logsWhereInput.schema';
import { order_logsOrderByWithAggregationInputObjectSchema as order_logsOrderByWithAggregationInputObjectSchema } from './objects/order_logsOrderByWithAggregationInput.schema';
import { order_logsScalarWhereWithAggregatesInputObjectSchema as order_logsScalarWhereWithAggregatesInputObjectSchema } from './objects/order_logsScalarWhereWithAggregatesInput.schema';
import { OrderLogsScalarFieldEnumSchema } from './enums/OrderLogsScalarFieldEnum.schema';
import { Order_logsCountAggregateInputObjectSchema as Order_logsCountAggregateInputObjectSchema } from './objects/Order_logsCountAggregateInput.schema';
import { Order_logsMinAggregateInputObjectSchema as Order_logsMinAggregateInputObjectSchema } from './objects/Order_logsMinAggregateInput.schema';
import { Order_logsMaxAggregateInputObjectSchema as Order_logsMaxAggregateInputObjectSchema } from './objects/Order_logsMaxAggregateInput.schema';
import { Order_logsAvgAggregateInputObjectSchema as Order_logsAvgAggregateInputObjectSchema } from './objects/Order_logsAvgAggregateInput.schema';
import { Order_logsSumAggregateInputObjectSchema as Order_logsSumAggregateInputObjectSchema } from './objects/Order_logsSumAggregateInput.schema';

export const order_logsGroupBySchema: z.ZodType<Prisma.order_logsGroupByArgs> = z.object({ where: order_logsWhereInputObjectSchema.optional(), orderBy: z.union([order_logsOrderByWithAggregationInputObjectSchema, order_logsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: order_logsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(OrderLogsScalarFieldEnumSchema), _count: z.union([ z.literal(true), Order_logsCountAggregateInputObjectSchema ]).optional(), _min: Order_logsMinAggregateInputObjectSchema.optional(), _max: Order_logsMaxAggregateInputObjectSchema.optional(), _avg: Order_logsAvgAggregateInputObjectSchema.optional(), _sum: Order_logsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.order_logsGroupByArgs>;

export const order_logsGroupByZodSchema = z.object({ where: order_logsWhereInputObjectSchema.optional(), orderBy: z.union([order_logsOrderByWithAggregationInputObjectSchema, order_logsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: order_logsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(OrderLogsScalarFieldEnumSchema), _count: z.union([ z.literal(true), Order_logsCountAggregateInputObjectSchema ]).optional(), _min: Order_logsMinAggregateInputObjectSchema.optional(), _max: Order_logsMaxAggregateInputObjectSchema.optional(), _avg: Order_logsAvgAggregateInputObjectSchema.optional(), _sum: Order_logsSumAggregateInputObjectSchema.optional() }).strict();