import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { error_reportsWhereInputObjectSchema as error_reportsWhereInputObjectSchema } from './objects/error_reportsWhereInput.schema';
import { error_reportsOrderByWithAggregationInputObjectSchema as error_reportsOrderByWithAggregationInputObjectSchema } from './objects/error_reportsOrderByWithAggregationInput.schema';
import { error_reportsScalarWhereWithAggregatesInputObjectSchema as error_reportsScalarWhereWithAggregatesInputObjectSchema } from './objects/error_reportsScalarWhereWithAggregatesInput.schema';
import { ErrorReportsScalarFieldEnumSchema } from './enums/ErrorReportsScalarFieldEnum.schema';
import { Error_reportsCountAggregateInputObjectSchema as Error_reportsCountAggregateInputObjectSchema } from './objects/Error_reportsCountAggregateInput.schema';
import { Error_reportsMinAggregateInputObjectSchema as Error_reportsMinAggregateInputObjectSchema } from './objects/Error_reportsMinAggregateInput.schema';
import { Error_reportsMaxAggregateInputObjectSchema as Error_reportsMaxAggregateInputObjectSchema } from './objects/Error_reportsMaxAggregateInput.schema';
import { Error_reportsAvgAggregateInputObjectSchema as Error_reportsAvgAggregateInputObjectSchema } from './objects/Error_reportsAvgAggregateInput.schema';
import { Error_reportsSumAggregateInputObjectSchema as Error_reportsSumAggregateInputObjectSchema } from './objects/Error_reportsSumAggregateInput.schema';

export const error_reportsGroupBySchema: z.ZodType<Prisma.error_reportsGroupByArgs> = z.object({ where: error_reportsWhereInputObjectSchema.optional(), orderBy: z.union([error_reportsOrderByWithAggregationInputObjectSchema, error_reportsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: error_reportsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ErrorReportsScalarFieldEnumSchema), _count: z.union([ z.literal(true), Error_reportsCountAggregateInputObjectSchema ]).optional(), _min: Error_reportsMinAggregateInputObjectSchema.optional(), _max: Error_reportsMaxAggregateInputObjectSchema.optional(), _avg: Error_reportsAvgAggregateInputObjectSchema.optional(), _sum: Error_reportsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.error_reportsGroupByArgs>;

export const error_reportsGroupByZodSchema = z.object({ where: error_reportsWhereInputObjectSchema.optional(), orderBy: z.union([error_reportsOrderByWithAggregationInputObjectSchema, error_reportsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: error_reportsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ErrorReportsScalarFieldEnumSchema), _count: z.union([ z.literal(true), Error_reportsCountAggregateInputObjectSchema ]).optional(), _min: Error_reportsMinAggregateInputObjectSchema.optional(), _max: Error_reportsMaxAggregateInputObjectSchema.optional(), _avg: Error_reportsAvgAggregateInputObjectSchema.optional(), _sum: Error_reportsSumAggregateInputObjectSchema.optional() }).strict();