import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { step_triggersWhereInputObjectSchema as step_triggersWhereInputObjectSchema } from './objects/step_triggersWhereInput.schema';
import { step_triggersOrderByWithAggregationInputObjectSchema as step_triggersOrderByWithAggregationInputObjectSchema } from './objects/step_triggersOrderByWithAggregationInput.schema';
import { step_triggersScalarWhereWithAggregatesInputObjectSchema as step_triggersScalarWhereWithAggregatesInputObjectSchema } from './objects/step_triggersScalarWhereWithAggregatesInput.schema';
import { StepTriggersScalarFieldEnumSchema } from './enums/StepTriggersScalarFieldEnum.schema';
import { Step_triggersCountAggregateInputObjectSchema as Step_triggersCountAggregateInputObjectSchema } from './objects/Step_triggersCountAggregateInput.schema';
import { Step_triggersMinAggregateInputObjectSchema as Step_triggersMinAggregateInputObjectSchema } from './objects/Step_triggersMinAggregateInput.schema';
import { Step_triggersMaxAggregateInputObjectSchema as Step_triggersMaxAggregateInputObjectSchema } from './objects/Step_triggersMaxAggregateInput.schema';
import { Step_triggersAvgAggregateInputObjectSchema as Step_triggersAvgAggregateInputObjectSchema } from './objects/Step_triggersAvgAggregateInput.schema';
import { Step_triggersSumAggregateInputObjectSchema as Step_triggersSumAggregateInputObjectSchema } from './objects/Step_triggersSumAggregateInput.schema';

export const step_triggersGroupBySchema: z.ZodType<Prisma.step_triggersGroupByArgs> = z.object({ where: step_triggersWhereInputObjectSchema.optional(), orderBy: z.union([step_triggersOrderByWithAggregationInputObjectSchema, step_triggersOrderByWithAggregationInputObjectSchema.array()]).optional(), having: step_triggersScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(StepTriggersScalarFieldEnumSchema), _count: z.union([ z.literal(true), Step_triggersCountAggregateInputObjectSchema ]).optional(), _min: Step_triggersMinAggregateInputObjectSchema.optional(), _max: Step_triggersMaxAggregateInputObjectSchema.optional(), _avg: Step_triggersAvgAggregateInputObjectSchema.optional(), _sum: Step_triggersSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.step_triggersGroupByArgs>;

export const step_triggersGroupByZodSchema = z.object({ where: step_triggersWhereInputObjectSchema.optional(), orderBy: z.union([step_triggersOrderByWithAggregationInputObjectSchema, step_triggersOrderByWithAggregationInputObjectSchema.array()]).optional(), having: step_triggersScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(StepTriggersScalarFieldEnumSchema), _count: z.union([ z.literal(true), Step_triggersCountAggregateInputObjectSchema ]).optional(), _min: Step_triggersMinAggregateInputObjectSchema.optional(), _max: Step_triggersMaxAggregateInputObjectSchema.optional(), _avg: Step_triggersAvgAggregateInputObjectSchema.optional(), _sum: Step_triggersSumAggregateInputObjectSchema.optional() }).strict();