import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { process_template_stepsSelectObjectSchema as process_template_stepsSelectObjectSchema } from './objects/process_template_stepsSelect.schema';
import { process_template_stepsIncludeObjectSchema as process_template_stepsIncludeObjectSchema } from './objects/process_template_stepsInclude.schema';
import { process_template_stepsWhereUniqueInputObjectSchema as process_template_stepsWhereUniqueInputObjectSchema } from './objects/process_template_stepsWhereUniqueInput.schema';
import { process_template_stepsCreateInputObjectSchema as process_template_stepsCreateInputObjectSchema } from './objects/process_template_stepsCreateInput.schema';
import { process_template_stepsUncheckedCreateInputObjectSchema as process_template_stepsUncheckedCreateInputObjectSchema } from './objects/process_template_stepsUncheckedCreateInput.schema';
import { process_template_stepsUpdateInputObjectSchema as process_template_stepsUpdateInputObjectSchema } from './objects/process_template_stepsUpdateInput.schema';
import { process_template_stepsUncheckedUpdateInputObjectSchema as process_template_stepsUncheckedUpdateInputObjectSchema } from './objects/process_template_stepsUncheckedUpdateInput.schema';

export const process_template_stepsUpsertOneSchema: z.ZodType<Prisma.process_template_stepsUpsertArgs> = z.object({ select: process_template_stepsSelectObjectSchema.optional(), include: process_template_stepsIncludeObjectSchema.optional(), where: process_template_stepsWhereUniqueInputObjectSchema, create: z.union([ process_template_stepsCreateInputObjectSchema, process_template_stepsUncheckedCreateInputObjectSchema ]), update: z.union([ process_template_stepsUpdateInputObjectSchema, process_template_stepsUncheckedUpdateInputObjectSchema ]) }).strict() as unknown as z.ZodType<Prisma.process_template_stepsUpsertArgs>;

export const process_template_stepsUpsertOneZodSchema = z.object({ select: process_template_stepsSelectObjectSchema.optional(), include: process_template_stepsIncludeObjectSchema.optional(), where: process_template_stepsWhereUniqueInputObjectSchema, create: z.union([ process_template_stepsCreateInputObjectSchema, process_template_stepsUncheckedCreateInputObjectSchema ]), update: z.union([ process_template_stepsUpdateInputObjectSchema, process_template_stepsUncheckedUpdateInputObjectSchema ]) }).strict();