FROM node:22-alpine

WORKDIR /usr/src/api

# Copy only necessary files
COPY package*.json ./
RUN npm ci --only=production

# Generate Prisma Client
RUN npx prisma generate

ENV NODE_ENV=production
ENV PORT=3000

EXPOSE 3000

CMD ["node", "dist/src/main.js"]
