FROM node:22-alpine AS builder

WORKDIR /usr/src/api

COPY package*.json ./
RUN npm ci --only=production --ignore-scripts && npm cache clean --force

COPY . .

RUN npm run build

FROM node:22-alpine

WORKDIR /usr/src/api

COPY --from=builder /usr/src/api/dist ./dist
COPY --from=builder /usr/src/api/node_modules ./node_modules
COPY --from=builder /usr/src/api/prisma ./prisma

RUN npx prisma generate

ENV NODE_ENV=production
ENV PORT=3000

EXPOSE 3000

CMD ["node", "dist/src/main.js"]